import { createTsupConfig } from '../../tsup.base.config';

export default createTsupConfig({
  // Full build: library + UI + worker + dedicated workers
  dts: {
    entry: {
      index: 'src/index.ts',
      'shared/index': 'src/common/shared/index.ts',
      'ui/index': 'src/ui/index.ts',
      'worker/index': 'src/worker/public.ts',
      'services/index': 'src/services/index.ts',
      // worker entriesは内部型が多いため一旦除外
    },
  },
  entry: {
    index: 'src/index.ts',
    'shared/index': 'src/common/shared/index.ts',
    'ui/index': 'src/ui/index.ts',
    'worker/index': 'src/worker/index.ts',
    'services/index': 'src/services/index.ts',
  },
  external: [
    '@hierarchidb/auth-recovery',
    '@hierarchidb/auth-recovery/*',
    '@hierarchidb/batch',
    '@hierarchidb/batch-types',
    '@hierarchidb/batch-types/*',
    '@hierarchidb/batch/*',
    '@hierarchidb/common-api',
    '@hierarchidb/common-api/*',
    '@hierarchidb/common-auth',
    '@hierarchidb/common-auth/*',
    '@hierarchidb/common-types',
    '@hierarchidb/common-types/*',
    '@hierarchidb/download',
    '@hierarchidb/download/*',
    '@hierarchidb/folder-plugin',
    '@hierarchidb/folder-plugin/*',
    '@hierarchidb/plugin-runtime-services',
    '@hierarchidb/plugin-ui-sdk',
    '@hierarchidb/plugin-ui-sdk/*',
    '@hierarchidb/plugin-types',
    '@hierarchidb/plugin-types/*',
    '@hierarchidb/runtime-client',
    '@hierarchidb/runtime-client/*',
    '@hierarchidb/runtime-plugin-dialog',
    '@hierarchidb/runtime-plugin-dialog/*',
    '@hierarchidb/runtime-worker',
    '@hierarchidb/runtime-worker-factory',
    '@hierarchidb/runtime-worker/*',
    '@hierarchidb/tabular-store',
    '@hierarchidb/tabular-store/*',
    '@hierarchidb/ui-accordion-config',
    '@hierarchidb/ui-accordion-config/*',
    '@hierarchidb/ui-core',
    '@hierarchidb/ui-country-select',
    '@hierarchidb/ui-country-select/*',
    '@hierarchidb/ui-datasource',
    '@hierarchidb/ui-datasource/*',
    '@hierarchidb/ui-license',
    '@hierarchidb/ui-license/*',
    '@hierarchidb/ui-lru-splitview',
    '@hierarchidb/ui-lru-splitview/*',
    '@hierarchidb/util',
    '@hierarchidb/util/*',
    '@mui/icons-material',
    '@mui/icons-material/*',
    '@mui/material',
    '@mui/material/*',
    'dexie',
    'provider',
    'provider-dom',
    'react',
    'react-dom',
  ],splitting: false,
});
