import type { NodeId, TreeId } from '@hierarchidb/core-types';
import type { TreeNode } from '@hierarchidb/tree-api';
import type { TreeConsoleActionDeps } from '../types.ts';
import type { NavigationHelpers } from './navigation';
import { beforeEach, describe, expect, it, vi } from 'vitest';

vi.mock('@hierarchidb/components', () => ({
  notify: {
    error: vi.fn(),
  },
}));
vi.mock('@hierarchidb/plugin-base', () => ({
  PluginStepRegistry: {
    getInstance: vi.fn(() => ({
      getConfigProvider: vi.fn(() => undefined),
    })),
  },
}));
vi.mock('~/features/templates/nodeCreateTemplates', () => ({
  importNodeTemplateById: vi.fn(async () => ({ success: true })),
  parseNodeCreateAction: vi.fn((action: string) => {
    if (action === 'create:shape') {
      return { nodeType: 'shape' };
    }
    if (action === 'create:shape::preset:world-level0') {
      return { nodeType: 'shape', shapePresetId: 'world-level0' as const };
    }
    return null;
  }),
  resolveNodeCreateDefaults: vi.fn(() => ({
    name: 'New Shape',
    description: 'Generated by preset',
    draftPatch: { buildConfig: { foo: true }, processingConfig: { bar: true } },
  })),
  resolveNodeTemplateExecution: vi.fn(() => ({
    kind: 'shapePreset',
    presetId: 'world-level0' as const,
  })),
}));

import { createContextMenuAction } from './contextMenu.ts';

type MockTreeNodeUpdaterAPI = {
  updateTreeNodeDraftMetadata: ReturnType<typeof vi.fn>;
  updateTreeNodeDraftData: ReturnType<typeof vi.fn>;
};

type MockMutationAPI = {
  createNode: ReturnType<typeof vi.fn>;
};

type MockQueryAPI = {
  listChildren: ReturnType<typeof vi.fn>;
};

const flushAsync = async () => {
  await Promise.resolve();
  await Promise.resolve();
  await new Promise((resolve) => setTimeout(resolve, 0));
};

const buildNode = (): TreeNode =>
  ({
    id: 'r:folder-1' as NodeId,
    nodeType: 'folder',
    metadata: { name: 'Folder', description: '', tags: [] },
    draftMetadata: null,
    data: null,
    draftData: null,
    parentId: 'r:root' as NodeId,
    depth: 1,
    createdAt: 1,
    updatedAt: 1,
    version: 1,
  }) as TreeNode;

const createContext = (): {
  action: ReturnType<typeof createContextMenuAction>['handleContextMenuAction'];
  api: {
    getMutationAPI: ReturnType<typeof vi.fn>;
    getQueryAPI: ReturnType<typeof vi.fn>;
    getTreeNodeUpdaterAPI: ReturnType<typeof vi.fn>;
  };
  spies: {
    updateTreeNodeDraftMetadata: ReturnType<typeof vi.fn>;
    updateTreeNodeDraftData: ReturnType<typeof vi.fn>;
  };
} => {
  const updateTreeNodeDraftMetadata = vi.fn(async () => undefined);
  const updateTreeNodeDraftData = vi.fn(async () => undefined);
  const mutationAPI: MockMutationAPI = {
    createNode: vi
      .fn(async () => ({ success: true, nodeId: 'r:new-shape' as NodeId }))
      .mockName('createNode'),
  };
  const queryAPI: MockQueryAPI = {
    listChildren: vi.fn(async () => [] as TreeNode[]),
  };
  const updaterAPI: MockTreeNodeUpdaterAPI = {
    updateTreeNodeDraftMetadata,
    updateTreeNodeDraftData,
  };

  const getMutationAPI = vi.fn(async () => mutationAPI);
  const getQueryAPI = vi.fn(async () => queryAPI);
  const getTreeNodeUpdaterAPI = vi.fn(async () => updaterAPI);

  const client = {
    getMutationAPI,
    getQueryAPI,
    getTreeNodeUpdaterAPI,
  } as {
    getMutationAPI: () => Promise<MockMutationAPI>;
    getQueryAPI: () => Promise<MockQueryAPI>;
    getTreeNodeUpdaterAPI: () => Promise<MockTreeNodeUpdaterAPI>;
  };

  const navigation: NavigationHelpers = {
    navigateTo: vi.fn(),
    pushToNode: vi.fn(),
  };

  const deps: Omit<TreeConsoleActionDeps, 'searchMode' | 'searchTerm'> = {
    client,
    treeId: 'r' as TreeId,
    pageNodeId: 'r:root' as NodeId,
    pageTreeNode: buildNode(),
    pushPath: vi.fn(),
    selectedIds: [],
    expandedIds: [],
    translateWithFallback: vi.fn((_, fallback) => fallback),
    setState: vi.fn(),
    setSSOT: vi.fn(),
    ssot: {
      expandedIds: [],
      selectedIds: [],
    },
    loadChildrenOf: vi.fn(async () => undefined),
    refreshUndoRedo: vi.fn(async () => undefined),
    importExport: {
      detectFileFormat: vi.fn(() => 'json'),
      importFile: vi.fn(),
      exportNodes: vi.fn(async () => new Blob()),
    },
    teardownSubscription: vi.fn(async () => undefined),
    setupSubscription: vi.fn(async () => undefined),
  } as Omit<TreeConsoleActionDeps, 'searchMode' | 'searchTerm'>;

  const action = createContextMenuAction(
    {
      ...deps,
      searchMode: 'local',
      searchTerm: '',
    } as TreeConsoleActionDeps,
    {
      applyClipboard: vi.fn(),
      openEditDialog: vi.fn(),
      resolvePreviewGuardState: vi.fn(async () => ({ canOpen: true })),
      navigation,
    }
  );

  return {
    action: action.handleContextMenuAction,
    api: { getMutationAPI, getQueryAPI, getTreeNodeUpdaterAPI },
    spies: {
      updateTreeNodeDraftMetadata,
      updateTreeNodeDraftData,
    },
  };
};

describe('createContextMenuAction', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('sets buildRequired=true when creating shape via Create menu action', async () => {
    const { action, api, spies } = createContext();
    const targetNode = {
      id: 'r:folder-1' as NodeId,
      nodeType: 'folder',
      metadata: { name: 'Root Folder', description: '', tags: [] },
      draftMetadata: null,
    };

    action('create:shape', targetNode as unknown as Parameters<typeof action>[1], { source: 'speedDial' });
    await flushAsync();

    expect(api.getMutationAPI).toHaveBeenCalled();
    expect(api.getQueryAPI).toHaveBeenCalled();
    expect(api.getTreeNodeUpdaterAPI).toHaveBeenCalled();
    expect(spies.updateTreeNodeDraftMetadata).toHaveBeenCalledWith('r:new-shape', {
      buildMetadata: { buildRequired: true },
    });
    expect(spies.updateTreeNodeDraftData).not.toHaveBeenCalled();
  });

  it('sets buildRequired=true when creating shape from preset template action', async () => {
    const { action, api, spies } = createContext();
    const targetNode = {
      id: 'r:folder-1' as NodeId,
      nodeType: 'folder',
      metadata: { name: 'Root Folder', description: '', tags: [] },
      draftMetadata: null,
    };

    action(
      'create:shape::preset:world-level0',
      targetNode as unknown as Parameters<typeof action>[1],
      { source: 'speedDial' }
    );
    await flushAsync();

    expect(api.getMutationAPI).toHaveBeenCalled();
    expect(api.getQueryAPI).toHaveBeenCalled();
    expect(api.getTreeNodeUpdaterAPI).toHaveBeenCalledTimes(2);
    expect(spies.updateTreeNodeDraftMetadata).toHaveBeenCalledWith('r:new-shape', {
      buildMetadata: { buildRequired: true },
    });
    expect(spies.updateTreeNodeDraftData).toHaveBeenCalledWith(
      'r:new-shape',
      expect.objectContaining({
        buildConfig: expect.any(Object),
        processingConfig: expect.any(Object),
      })
    );
  });
});
