import { createTsupConfig } from "../../tsup.base.config";

export default createTsupConfig({
  entry: {
    'index': 'src/index.ts',
    'ui/index': 'src/ui/index.ts',
    'shared/index': 'src/common/shared/index.ts',
    'services/index': 'src/services/index.ts',
    'worker/index': 'src/worker/factory/index.ts',
  },
  dts: {
    entry: {
      'index': 'src/index.ts',
      'ui/index': 'src/ui/index.ts',
      'shared/index': 'src/common/shared/index.ts',
      'services/index': 'src/services/index.ts',
      'worker/index': 'src/worker/factory/index.ts',
    },
  },
  external: [
    '@hierarchidb/common-types',
    '@hierarchidb/common-types/*',
    '@hierarchidb/components',
    '@hierarchidb/components/*',
    '@hierarchidb/folder-plugin',
    '@hierarchidb/folder-plugin/*',
    '@hierarchidb/plugin-ui-sdk',
    '@hierarchidb/plugin-ui-sdk/*',
    '@hierarchidb/runtime-basic-info',
    '@hierarchidb/runtime-basic-info/*',
    '@hierarchidb/runtime-plugin-dialog',
    '@hierarchidb/runtime-plugin-dialog/*',
    '@hierarchidb/runtime-ui-plugin-dialog',
    '@hierarchidb/runtime-worker',
    '@hierarchidb/runtime-worker/*',
    '@hierarchidb/spreadsheet-plugin',
    '@hierarchidb/spreadsheet-plugin/*',
    '@hierarchidb/tabular-store',
    '@hierarchidb/tabular-store/*',
    '@hierarchidb/ui-csv-extract',
    '@hierarchidb/ui-tabular-extract',
    '@hierarchidb/ui-tabular-extract/*',
    '@hierarchidb/util',
    '@hierarchidb/util/*',
    '@mui/icons-material',
    '@mui/icons-material/*',
    '@mui/material',
    '@mui/material/*',
    'dexie',
    'i18next',
    'react',
    'react-dom',
    'react-i18next',
  ],});
