packages:
  - _app
  - packages/common/*
  - packages/runtime/*
  - packages/ui/*
  - packages/ui/treeconsole/*
  - packages/backend/*
  - packages/node-type-plugin/*
  - packages/feature-plugin/*

ignoredBuiltDependencies:
  - esbuild
  - sharp
  - workerd
