packages:
  - app
  - packages/components
  - packages/_obsolate_common/*
  - packages/util
  - packages/tools
  - packages/tools/*
  - packages/vite-plugins/*
  - app/vite-plugins/*
  - packages/testing/*
  - packages/memory
  - packages/common/*
  - packages/runtime-worker
  - packages/runtime-worker/*
  - packages/ui/*
  - packages/ui/treeconsole/*
  - packages/plugin-registry
  - packages/plugin-service-api
  - packages/plugin-service-sdk
  - packages/plugin-ui-host
  - packages/plugin-presentation
  - packages/plugin-base
  - packages/ui/plugin-shell
  - packages/backend/*
  - packages/features/*
  - packages/plugin-ui-sdk
  - packages/plugin-types
  - packages/batch-runtime-worker-services
  - packages/batch-runtime-services
  - packages/batch-types
  - packages/vt-*
  - plugins/*

ignoredBuiltDependencies:
  - esbuild
  - sharp
  - workerd
