/**
 * Type definitions for Shape plugin services
 */

import type { NodeId } from '@hierarchidb/common-types';
import type { Feature as GeoJSONFeature } from 'geojson';
import type {
  BoundingBox,
  CountryMetadata,
  DataSourceInfo,
  DataSourceName,
  DataSourceValidationResult,
} from '@hierarchidb/ui-datasource';
import type {
  DownloadTaskPayload,
  ErrorInfo as SharedErrorInfo,
  ProcessingStage,
  ProgressInfo as SharedProgressInfo,
  StageStatus as SharedStageStatus,
  TaskStatus,
} from '../common/types/index.js';

// === API Method Signatures ===

export interface ShapesAPIMethods {
  // Auth
  setAuthToken(token: string, type?: 'Bearer' | 'Basic', expiresAt?: number): Promise<void> | void;

  // Batch processing
  startBatchProcess(
    nodeId: NodeId,
    config: BatchProcessConfig,
    downloadTaskPayloads: DownloadTaskPayload[],
  ): Promise<BatchSession>;

  pauseBatchProcess(nodeId: NodeId): Promise<void>;

  resumeBatchProcess(nodeId: NodeId): Promise<void>;

  getBatchStatus(nodeId: NodeId): Promise<BatchStatus>;

  // Data sources
  getAvailableDataSources(): Promise<DataSourceInfo[]>;

  getCountryMetadata(nodeId: NodeId, dataSource: string, countryCode?: string): Promise<CountryMetadata[]>;

  validateDataSource(dataSource: string, config: DataSourceConfig): Promise<DataSourceValidationResult>;

  // Vector tiles
  getTile(nodeId: NodeId, z: number, x: number, y: number): Promise<Uint8Array>;

  getTileMetadata(nodeId: NodeId, z: number, x: number, y: number): Promise<TileMetadata>;

  clearTileCache(nodeId: NodeId): Promise<void>;

  // Feature queries
  searchFeatures(nodeId: NodeId, query: string, options?: SearchOptions): Promise<GeoJSONFeature[]>;

  getFeatureById(nodeId: NodeId, featureId: number): Promise<GeoJSONFeature | null>;

  getFeaturesByBbox(nodeId: NodeId, bbox: BoundingBox, options?: BboxQueryOptions): Promise<GeoJSONFeature[]>;

  // Cache management
  getCacheStatistics(nodeId?: NodeId): Promise<CacheStatistics>;

  clearCache(nodeId: NodeId, cacheType?: CacheType): Promise<void>;

  optimizeStorage(nodeId: NodeId): Promise<OptimizationResult>;

  // Vector tiles generated by runtime-worker worker (session-based)
  listGeneratedTiles(nodeId: NodeId): Promise<Array<{ z: number; x: number; y: number; size: number; timestamp: number }>>;
  getGeneratedTile(nodeId: NodeId, z: number, x: number, y: number): Promise<Uint8Array | null>;
  getGeneratedTileSummary(nodeId: NodeId): Promise<{ tiles: number; totalBytes: number; zoomMin?: number; zoomMax?: number }>;
}

// === Data Types ===

// Re-export types from runtime-worker/datasource for compatibility
export type {
  DataSourceName,
  DataSourceInfo,
  CountryMetadata,
  DataSourceValidationResult,
  BoundingBox,
};

export type CacheType =
  | 'features'
  | 'tiles'
  | 'buffers'
  | 'all';

// === Configuration Types ===

export interface BatchProcessConfig {
  dataSource: DataSourceName;
  countryCode: string;
  adminLevels: number[];
  workerPoolSize?: number;
  enableFeatureExtraction?: boolean;
  extractionLevels?: number[];
  tileZoomRange?: [number, number];
  corsProxy?: string;
  cacheStrategy?: CacheStrategy;
}

export interface CacheStrategy {
  enableCache: boolean;
  ttl?: number; // Time to live in seconds
  maxSize?: number; // Max cache size in bytes
  compressionLevel?: number; // 0-9
}

export interface DataSourceConfig {
  countryCode: string;
  adminLevels: number[];
  filterRules?: FilterRule[];
  bbox?: BoundingBox;
}

export type FilterValue = string | number | boolean | Array<string | number | boolean> | null;

export interface FilterRule {
  field: string;
  operator: 'eq' | 'ne' | 'gt' | 'lt' | 'gte' | 'lte' | 'in' | 'contains' | 'regex';
  value: FilterValue;
  caseSensitive?: boolean;
}

// === Session & Status Types ===

export interface BatchSession {
  nodeId: NodeId;
  status: 'idle' | 'running' | 'paused' | 'completed' | 'failed';
  config: BatchProcessConfig;
  startedAt: number;
  updatedAt: number;
  completedAt?: number;
  progress: ProgressInfo;
  stages: Record<ProcessingStage, StageStatus>;
  resourceUsage?: ResourceUsage;
}

export interface BatchStatus {
  session: BatchSession;
  currentTasks: TaskInfo[];
  queuedTasks: number;
  errors: ErrorInfo[];
  warnings: string[];
  estimatedTimeRemaining?: number;
  throughput?: {
    tasksPerSecond: number;
    bytesPerSecond: number;
  };
}

export type ProgressInfo = SharedProgressInfo;

export interface StageStatus extends SharedStageStatus {
  startedAt?: number;
  completedAt?: number;
  lastError?: string;
}

export interface TaskInfo {
  taskId: string;
  nodeId: NodeId;
  type: ProcessingStage;
  status: TaskStatus;
  index: number;
  progress: number;
  message?: string;
  retryCount?: number;
}

export interface ErrorInfo extends SharedErrorInfo {
  stack?: string;
}

export interface ResourceUsage {
  memoryUsed: number;
  memoryPeak: number;
  cpuPercent: number;
  storageUsed: number;
  networkBytesReceived: number;
  networkBytesSent: number;
}

// === Data Source Types ===
// Types imported from @hierarchidb/runtime-worker-ui-datasource

export interface ValidationError {
  code: string;
  message: string;
  field?: string;
}

export interface ValidationWarning {
  code: string;
  message: string;
  suggestion?: string;
}

// === Tile Types ===

export interface TileMetadata {
  exists: boolean;
  nodeId: NodeId;
  tileKey: string;
  z: number;
  x: number;
  y: number;
  size: number;
  features: number;
  layers: LayerInfo[];
  generatedAt: number;
  lastAccessed?: number;
  contentHash: string;
  contentEncoding?: 'gzip' | 'br';
  version: number;
}

export interface LayerInfo {
  name: string;
  featureCount: number;
  minZoom: number;
  maxZoom: number;
  fields: string[];
}

// === Feature Types ===

export type Feature = GeoJSONFeature;

export interface SearchOptions {
  limit?: number;
  offset?: number;
  adminLevel?: number;
  countryCode?: string;
  fuzzy?: boolean;
  sortBy?: 'name' | 'population' | 'area' | 'relevance';
  sortOrder?: 'asc' | 'desc';
}

export interface BboxQueryOptions {
  limit?: number;
  offset?: number;
  adminLevel?: number;
  extractionLevel?: number;
  includeProperties?: boolean;
  clip?: boolean;
}

// === Cache Types ===

export interface CacheStatistics {
  totalSize: number;
  totalItems: number;
  byType: Record<CacheType, CacheTypeStats>;
  hitRate: number;
  missRate: number;
  evictionCount: number;
  oldestItem: number;
  newestItem: number;
  lastCleanup?: number;
}

export interface CacheTypeStats {
  size: number;
  count: number;
  hits: number;
  misses: number;
  evictions: number;
  averageSize: number;
}

export interface OptimizationResult {
  freedSpace: number;
  removedItems: number;
  compactedItems: number;
  duration: number;
  errors: string[];
  suggestions: string[];
}

// (Legacy Worker Pool types removed)

export type {
  DownloadTask,
  //DownloadTaskInput,
  ExtractTask,
  Extract1Task,
  Extract2Task,
  //ExtractTaskInput,
  TileExtractConfig,
  VectorTileTask,
  //VectorTileTaskInput,
  ProcessingStage,
  TaskStatus,
} from '../common/types/index.js';

export interface DownloadResult {
  taskId: string;
  status: 'completed' | 'failed';
  outputBufferId: string;
  featureCount: number;
  downloadTime: number;
  downloadSize: number;
  compressionRatio: number;
  spatialIndices: FeatureIndex[];
  errorMessage?: string;
}

export interface Extract1Result {
  taskId: string;
  status: 'completed' | 'failed';
  outputBufferId: string;
  originalFeatureCount: number;
  extractedFeatureCount: number;
  reductionRatio: number;
  qualityMetrics: QualityMetrics;
  errorMessage?: string;
}

export interface Extract2Result {
  taskId: string;
  status: 'completed' | 'failed';
  tileBufferIds: string[];
  tilesGenerated: number;
  topologyPreserved: boolean;
  errorMessage?: string;
}

export interface VectorTileResult {
  taskId: string;
  status: 'completed' | 'failed';
  tileId: string;
  mvtSize: number;
  featureCount: number;
  compressionRatio?: number;
  qualityScore: number;
  errorMessage?: string;
}

// (Legacy Worker API interfaces removed)

// === Supporting Types ===

export interface FeatureIndex {
  indexId: string;
  featureId: string;
  mortonCode: number;
  bbox: [number, number, number, number];
  centroid: [number, number];
  area: number;
  complexity: number;
}

export interface QualityMetrics {
  geometricAccuracy: number;
  topologicalIntegrity: number;
  visualQuality: number;
  compressionEfficiency: number;
}

export interface LayerConfig {
  name: string;
  minZoom: number;
  maxZoom: number;
  properties: string[];
  extractionLevel: number;
}

export interface TopoJSONTopology {
  type: 'Topology';
  arcs: number[][][];
  objects: Record<string, TopoJSONObject>;
  transform?: {
    scale: [number, number];
    translate: [number, number];
  };
}

export interface TopoJSONObject {
  type: 'GeometryCollection';
  geometries: TopoJSONGeometry[];
}

export interface TopoJSONGeometry {
  type: string;
  properties?: Record<string, string | number | boolean | null>;
  id?: string | number;
  arcs?: number[][];
}

export interface TopoJSONResult {
  topology: TopoJSONTopology;
  objects: Record<string, TopoJSONObject>;
  transform?: {
    scale: [number, number];
    translate: [number, number];
  };
  quantization: number;
}

export interface TopologyValidationResult {
  isValid: boolean;
  sharedBoundariesPreserved: boolean;
  selfIntersections: number;
  invalidGeometries: string[];
  topologyErrors: string[];
}

// === Worker Message Types ===

export interface WorkerMessage<TParams = unknown, TResult = unknown> {
  type: 'request' | 'response' | 'progress' | 'error' | 'cancel';
  id: string;
  method?: string;
  params?: TParams;
  result?: TResult;
  error?: WorkerError;
  progress?: WorkerProgress;
}

export interface WorkerError {
  code: string;
  message: string;
  stack?: string;
  data?: Record<string, unknown>;
}

export interface WorkerProgress {
  taskId: string;
  stage: ProcessingStage;
  current: number;
  total: number;
  message?: string;
  subProgress?: {
    current: number;
    total: number;
    message: string;
  };
}

// === Feature Data Types ===

export interface FeatureData {
  id: string;
  geometry: GeoJSON.Geometry;
  properties: Record<string, string | number | boolean | null>;
  metadata: FeatureMetadata;
}

export interface FeatureMetadata {
  originalId: string;
  dataSource: string;
  downloadedAt: number;
  extractionLevel: number;
  qualityScore: number;
  bbox: [number, number, number, number];
}
