export type TaskPhaseLabel = { key: string; fallback: string };

export const taskPhaseLabels = new Map<string, TaskPhaseLabel>([
  ['fetch-cache:start', { key: 'stage.taskPhase.fetchCacheStart', fallback: 'Fetch cache start' }],
  ['fetch-cache:done', { key: 'stage.taskPhase.fetchCacheDone', fallback: 'Fetch cache done' }],
  ['decode:start', { key: 'stage.taskPhase.decodeStart', fallback: 'Decode start' }],
  ['decode:done', { key: 'stage.taskPhase.decodeDone', fallback: 'Decode done' }],
  ['filtering:start', { key: 'stage.taskPhase.filteringStart', fallback: 'Filtering start' }],
  ['filtering:done', { key: 'stage.taskPhase.filteringDone', fallback: 'Filtering done' }],
  ['prepare:counts:start', { key: 'stage.taskPhase.prepareCountsStart', fallback: 'Prepare counts start' }],
  ['prepare:counts:done', { key: 'stage.taskPhase.prepareCountsDone', fallback: 'Prepare counts done' }],
  ['simplify:start', { key: 'stage.taskPhase.simplifyStart', fallback: 'Simplify start' }],
  ['simplify:done', { key: 'stage.taskPhase.simplifyDone', fallback: 'Simplify done' }],
  ['simplify:preprocess:start', { key: 'stage.taskPhase.simplifyPreprocessStart', fallback: 'Preprocess start' }],
  ['simplify:preprocess:done', { key: 'stage.taskPhase.simplifyPreprocessDone', fallback: 'Preprocess done' }],
  ['simplify:selfIntersection:start', { key: 'stage.taskPhase.simplifySelfIntersectionStart', fallback: 'Self-intersection fix start' }],
  ['simplify:selfIntersection:done', { key: 'stage.taskPhase.simplifySelfIntersectionDone', fallback: 'Self-intersection fix done' }],
  ['simplify:simplify:start', { key: 'stage.taskPhase.simplifyGeometryStart', fallback: 'Geometry simplify start' }],
  ['simplify:simplify:done', { key: 'stage.taskPhase.simplifyGeometryDone', fallback: 'Geometry simplify done' }],
  ['output:build:start', { key: 'stage.taskPhase.outputBuildStart', fallback: 'Output build start' }],
  ['output:build:done', { key: 'stage.taskPhase.outputBuildDone', fallback: 'Output build done' }],
  ['output:counts:start', { key: 'stage.taskPhase.outputCountsStart', fallback: 'Output counts start' }],
  ['encode:start', { key: 'stage.taskPhase.encodeStart', fallback: 'Encode start' }],
  ['encode:done', { key: 'stage.taskPhase.encodeDone', fallback: 'Encode done' }],
  ['cache:put:start', { key: 'stage.taskPhase.cachePutStart', fallback: 'Cache write start' }],
  ['cache:put:done', { key: 'stage.taskPhase.cachePutDone', fallback: 'Cache write done' }],
]);
