import { createTsupConfig } from '../../../../tsup.base.config.js';

export default createTsupConfig({
  external: [
    '@dnd-kit/core',
    '@dnd-kit/core/*',
    '@dnd-kit/modifiers',
    '@dnd-kit/modifiers/*',
    '@dnd-kit/sortable',
    '@dnd-kit/sortable/*',
    '@dnd-kit/utilities',
    '@dnd-kit/utilities/*',
    '@emotion/react',
    '@emotion/react/*',
    '@emotion/styled',
    '@emotion/styled/*',
    '@hierarchidb/common-api',
    '@hierarchidb/common-api/*',
    '@hierarchidb/common-types',
    '@hierarchidb/common-types/*',
    '@hierarchidb/ui-icon',
    '@hierarchidb/ui-icon/*',
    '@hierarchidb/ui-theme',
    '@hierarchidb/ui-theme/*',
    '@hierarchidb/ui-treeconsole-breadcrumb',
    '@hierarchidb/ui-treeconsole-breadcrumb/*',
    '@hierarchidb/ui-treeconsole-footer',
    '@hierarchidb/ui-treeconsole-footer/*',
    '@hierarchidb/ui-treeconsole-toolbar',
    '@hierarchidb/ui-treeconsole-toolbar/*',
    '@hierarchidb/ui-treeconsole-trashbin',
    '@hierarchidb/ui-treeconsole-trashbin/*',
    '@hierarchidb/ui-treeconsole-treetable',
    '@hierarchidb/ui-treeconsole-treetable/*',
    '@mui/icons-material',
    '@mui/icons-material/*',
    '@mui/material',
    '@mui/material/*',
    '@tanstack/react-table',
    '@tanstack/react-table/*',
    '@tanstack/react-virtual',
    '@tanstack/react-virtual/*',
    'comlink',
    'jotai',
    'react',
    'react-dom',
    'rxjs',
  ],});
