// scripts/split-with-deps.ts
// pnpm add -D ts-morph globby minimist change-case tsx
//  :
//   pnpm tsx scripts/split-with-deps.ts --root src --tsconfig tsconfig.json --dry-run=true
//   pnpm tsx scripts/split-with-deps.ts --root src --exclude "**/examples/**,**/*.demo.tsx" --dry-run=false

import {
  ExportedDeclarations,
  ImportDeclaration,
  Node,
  Project,
  SourceFile,
  Statement,
  Symbol as TsSymbol,
  SyntaxKind,
} from 'ts-morph';
import { globby } from 'globby';
import minimist from 'minimist';
import path from 'node:path';
import fs from 'node:fs/promises';
import { pascalCase } from 'change-case';

type Args = {
  root?: string;
  tsconfig?: string;
  dryRun?: boolean | string;
  exclude?: string | string[];
};

const rel = (p: string) => p.replaceAll(path.sep, '/');
const getFileStem = (p: string) => path.basename(p).replace(/\.(tsx|ts)$/i, '');
const unique = <T,>(arr: T[]) => Array.from(new Set(arr));

/**
  */
const DEFAULT_EXCLUDES = [
  '**/*.d.ts',
  '**/*.backup',
  '**/index.ts',
  '**/__tests__/**',
  '**/__mocks__/**',
  '**/*.stories.{ts,tsx}',
  '**/*.{test,spec}.{ts,tsx}',

  //  *.config.ts / *config.ts
  '**/*config.{ts,tsx}',
  '**/*.config.{ts,tsx}',
  '**/eslint.config.{ts,js,cjs,mjs}', '**/vite.config.{ts,tsx,js,cjs,mjs}',
  '**/vitest.config.{ts,tsx,js,cjs,mjs}',
  '**/playwright.config.{ts,tsx,js,cjs,mjs}',
  '**/tsup.config.{ts,tsx,js,cjs,mjs}',
  '**/rollup.config.{ts,tsx,js,cjs,mjs}',
  '**/tailwind.config.{ts,tsx,js,cjs,mjs}',

  '**/node_modules/**',
  '**/dist/**',
  '**/build/**',
  '**/.next/**',
  '**/.nuxt/**',
  '**/.output/**',
  '**/.vercel/**',
  '**/coverage/**',
  '**/.turbo/**',
  '**/.cache/**',
  '**/out/**',
  '**/cypress/**',
  '**/.storybook/**',
];

/**
 * @nosplit
 */
function hasNoSplitGuard(sf: SourceFile): boolean {
  const text = sf.getFullText();
  const head = text.slice(0, 2048);
  return /^\s*\/\/\s*@nosplit\b/m.test(head);
}

/**
  */
function isGeneratedByOurTool(sf: SourceFile): boolean {
  const text = sf.getFullText();
  const head = text.slice(0, 2048);
  return /@generated by split-with-deps/.test(head);
}

/*
function isTypeDecl(d: ExportedDeclarations) {
  return Node.isInterfaceDeclaration(d) || Node.isTypeAliasDeclaration(d);
}
function isValueDecl(d: ExportedDeclarations) {
  return (
    Node.isClassDeclaration(d) ||
    Node.isFunctionDeclaration(d) ||
    Node.isEnumDeclaration(d) ||
    Node.isVariableDeclaration(d)
  );
}
 */

function collectOwnExports(sf: SourceFile) {
  const direct = sf.getExportedDeclarations();
  const hasOwn = [...direct.values()].flat().some((d) => d.getSourceFile() === sf);
  if (!hasOwn && sf.getDefaultExportSymbol()) {
    const def = sf.getDefaultExportSymbol();
    const decls: Node[] = def?.getDeclarations() ?? [];
    if (!decls.some((d) => d.getSourceFile() === sf)) return null;
  }
  return direct;
}

function getDefaultExportName(sf: SourceFile): string | null {
  const def = sf.getDefaultExportSymbol();
  if (!def) return null;
  const decl = def.getDeclarations()?.[0];
  if (decl) {
    if (Node.isFunctionDeclaration(decl) || Node.isClassDeclaration(decl)) {
      const name = decl.getName();
      if (name) return name;
    }
  }
  return pascalCase(getFileStem(sf.getFilePath()));
}

function collectLocalDependencyDeclarations(targets: Node[], sf: SourceFile): Statement[] {
  const checker = sf.getProject().getTypeChecker();
  const queue: Node[] = [...targets];
  const seenDeclPos = new Set<number>();
  const depStatements: Statement[] = [];

  const exportedDecls = new Set<number>();
  sf.getExportedDeclarations().forEach((decls) => {
    decls.forEach((d) => exportedDecls.add(d.getStart()));
  });

  function addDeclStatementIfNeeded(d: Node) {
    let stmt: Statement | undefined;
    if (Node.isVariableDeclaration(d)) {
      stmt = d.getVariableStatement() ?? d.getFirstAncestorByKind(SyntaxKind.VariableStatement);
    } else {
      stmt =
        d.getFirstAncestorByKind(SyntaxKind.IfStatement) ??
        ((Node.isStatement(d) ? d : undefined) as Statement | undefined);
    }
    if (!stmt) return;
    const pos = stmt.getStart();
    if (seenDeclPos.has(pos)) return;
    seenDeclPos.add(pos);
    depStatements.push(stmt);
  }

  while (queue.length) {
    const node = queue.pop()!;
    for (const id of node.getDescendantsOfKind(SyntaxKind.Identifier)) {
      const sym: TsSymbol | undefined = id.getSymbol() ?? checker.getSymbolAtLocation(id);
      if (!sym) continue;
      const decls = sym.getDeclarations();
      if (!decls || decls.length === 0) continue;

      //  import
      const fromImport = decls.some(
        (d) =>
          (d.getParent() && Node.isImportClause(d.getParent())) ||
          Node.isImportSpecifier(d) ||
          Node.isNamespaceImport(d),
      );
      if (fromImport) continue;

      const localDecl = decls.find((d) => d.getSourceFile() === sf);
      if (!localDecl) continue;

      if (exportedDecls.has(localDecl.getStart())) continue;

      addDeclStatementIfNeeded(localDecl);
      queue.push(localDecl);
    }
  }

  depStatements.sort((a, b) => a.getStart() - b.getStart());
  for (let pass = 0; pass < 2; pass++) {
    for (let i = 0; i < depStatements.length; i++) {
      const A = depStatements[i];
      const ids = A?.getDescendantsOfKind(SyntaxKind.Identifier);
      const nameSet = new Set(ids?.map((x) => x.getText()));
      for (let j = i + 1; j < depStatements.length; j++) {
        const B = depStatements[j];
        const bName =
          Node.isFunctionDeclaration(B) ||
          Node.isClassDeclaration(B) ||
          Node.isInterfaceDeclaration(B) ||
          Node.isTypeAliasDeclaration(B) ||
          Node.isEnumDeclaration(B)
            ? (B.getName?.() ?? '')
            : Node.isVariableStatement(B)
              ? B.getDeclarations()
                .map((d) => d.getName())
                .join('|')
              : '';
        if (bName && nameSet.has(bName)) {
          const tmp = depStatements[i];
          if (depStatements[i] && depStatements[j]) {
            depStatements[i] = depStatements[j] as Statement;
          }
          if (tmp) depStatements[j] = tmp;
        }
      }
    }
  }

  return depStatements;
}

function pickUsedImports(sf: SourceFile, includedNodes: Node[]): ImportDeclaration[] {
  const usedNames = new Set<string>();
  includedNodes.forEach((n) => {
    n.getDescendantsOfKind(SyntaxKind.Identifier).forEach((id) => usedNames.add(id.getText()));
  });

  const imports: ImportDeclaration[] = [];
  for (const imp of sf.getImportDeclarations()) {
    if (!imp.getImportClause()) {
      //  import
      imports.push(imp);
      continue;
    }
    const ns = imp.getNamespaceImport();
    const def = imp.getDefaultImport();
    const named = imp.getNamedImports();

    let keep = false;
    if (ns && usedNames.has(ns.getText())) keep = true;
    if (def && usedNames.has(def.getText())) keep = true;
    if (!keep) {
      for (const ni of named) {
        const local = ni.getNameNode().getText();
        const alias = ni.getAliasNode()?.getText();
        if (usedNames.has(alias ?? local)) {
          keep = true;
          break;
        }
      }
    }
    if (keep) imports.push(imp);
  }
  return imports;
}

function normalizeExcludeArg(excludeArg?: string | string[]): string[] {
  if (!excludeArg) return [];
  const arr = Array.isArray(excludeArg) ? excludeArg : String(excludeArg).split(',');
  return arr.map((s) => s.trim()).filter(Boolean);
}

async function main() {
  const argv = minimist(process.argv.slice(2)) as unknown as Args;
  const ROOT = argv.root ?? 'src';
  const TSCONFIG = argv.tsconfig ?? 'tsconfig.json';
  const DRY = String(argv.dryRun ?? 'true') === 'true';
  const EXTRA_EXCLUDES = normalizeExcludeArg(argv.exclude);

  const project = new Project({ tsConfigFilePath: TSCONFIG });

  //  globby include / exclude
  const ROOT_POSIX = ROOT.replaceAll(path.sep, '/');
  const includeGlobs = [`${ROOT_POSIX}/**/*.{ts,tsx}`];
  const excludeGlobs = [...DEFAULT_EXCLUDES, ...EXTRA_EXCLUDES].map((p) => {
    const pat = p.replace(/^!+/, '');
    return `!${pat.startsWith('**/') ? `${ROOT_POSIX}/${pat.slice(3)}` : pat.startsWith(ROOT_POSIX) ? pat : `${ROOT_POSIX}/${pat}`}`;
  });

  const patterns = [...includeGlobs, ...excludeGlobs];

  const files = await globby(patterns, { absolute: true });

  for (const absPath of files) {
    const sf = project.addSourceFileAtPath(absPath);

    if (hasNoSplitGuard(sf)) {
      console.log(`SKIP @nosplit: ${rel(absPath)}`);
      continue;
    }
    if (isGeneratedByOurTool(sf)) {
      console.log(`SKIP generated: ${rel(absPath)}`);
      continue;
    }

    const own = collectOwnExports(sf);
    if (!own && !sf.getDefaultExportSymbol()) continue;

    //const base = path.basename(absPath);
    const dir = path.dirname(absPath);
    const ext = path.extname(absPath);
    const stem = getFileStem(absPath);

    const exportsMap = new Map<string, ExportedDeclarations[]>();
    (own ?? new Map()).forEach((decls, name) => {
      const inThis = decls.filter((d: any) => d.getSourceFile() === sf);
      if (inThis.length) exportsMap.set(name, inThis);
    });

    let defaultName: string | null = null;
    if (sf.getDefaultExportSymbol()) {
      defaultName = getDefaultExportName(sf);
      if (defaultName) {
        const decl = sf.getDefaultExportSymbol()!.getDeclarations()?.[0];
        if (decl && decl.getSourceFile() === sf) {
          exportsMap.set('__DEFAULT__', [decl as ExportedDeclarations]);
        }
      }
    }

    if (exportsMap.size === 0) continue;

    //  .backup
    const backupPath = path.join(dir, `${stem}${ext}.backup`);
    if (!DRY) await fs.rename(absPath, backupPath);
    console.log(`RENAMED: ${rel(absPath)} -> ${rel(backupPath)}`);

    const shimLines: string[] = [];

    for (const [rawName, decls] of exportsMap) {
      const decl =
        decls.find((d) => (Node.isFunctionDeclaration(d) ? !!d.getBody() : true)) ?? decls[0];

      if (!decl) {
        continue;
      }

      const symName = rawName === '__DEFAULT__' ? (defaultName ?? 'DefaultExport') : rawName;

      const deps = collectLocalDependencyDeclarations([decl], decl.getSourceFile());
      const usedImports = pickUsedImports(decl.getSourceFile(), [...deps, decl]);

      const header = `/* @generated by split-with-deps: ${rel(absPath)} -> ${symName}${ext} */\n`;
      const importsText = usedImports.map((i) => i.getText()).join('\n');
      const depsText = deps.map((s) => s.getText()).join('\n\n');

      let bodyText = decl.getText();
      if ('getModifiers' in decl && typeof (decl as any).getModifiers === 'function') {
        (decl as any).getModifiers().forEach((m: any) => {
          if (m.getText() === 'export' || m.getText() === 'default') m.remove();
        });
      } else {
        bodyText = bodyText.replace(/\bexport\s+default\b/, '').replace(/\bexport\s+/, '');
      }

      if (rawName === '__DEFAULT__') {
        if (Node.isFunctionDeclaration(decl) && !decl.getName()) {
          bodyText = bodyText.replace(/^function\b/, `function ${symName}`);
        }
        if (Node.isClassDeclaration(decl) && !decl.getName()) {
          bodyText = bodyText.replace(/^class\b/, `class ${symName}`);
        }
      }

      const exportedBody = bodyText.startsWith('declare ')
        ? bodyText
        : bodyText.replace(/^(?=(class|function|interface|type|enum|const|let|var)\b)/, 'export ');

      const content = [
        header,
        importsText,
        importsText ? '\n' : '',
        depsText,
        depsText ? '\n\n' : '',
        exportedBody,
        '\n',
      ].join('');

      const targetPath = path.join(dir, `${symName}${ext}`);
      if (!DRY) await fs.writeFile(targetPath, content, 'utf8');
      console.log(
        `WRITE:   ${rel(targetPath)} (with ${deps.length} local deps, ${usedImports.length} imports)`,
      );

      if (rawName === '__DEFAULT__') {
        shimLines.push(`export { ${symName} as default } from './${symName}.js';`);
      } else {
        shimLines.push(`export { ${symName} } from './${symName}.js';`);
      }
    }

    //  shim
    const shimPath = path.join(dir, `${stem}${ext}`);
    const shimContent = shimLines.join('\n') + '\n';
    if (!DRY) await fs.writeFile(shimPath, shimContent, 'utf8');
    console.log(`SHIM:    ${rel(shimPath)}`);

    //  index.ts
    const indexPath = path.join(dir, 'index.ts');
    let indexLines: string[] = [];
    try {
      const prev = await fs.readFile(indexPath, 'utf8');
      indexLines = prev.split(/\r?\n/).filter(Boolean);
    } catch {
    }
    for (const line of shimLines) {
      const m = line.match(/export\s+\{\s*(.+?)\s*\}\s+from\s+'\.\/(.+?)';/);
      if (!m) continue;
      const names = m[1];
      const file = m[2];
      if (names?.includes(' as default')) {
        const nm = names.replace(/\s+as\s+default/, '');
        const idxLine = `export { ${nm} } from './${file}.js';`;
        if (!indexLines.includes(idxLine)) indexLines.push(idxLine);
      } else {
        const idxLine = `export { ${names} } from './${file}.js';`;
        if (!indexLines.includes(idxLine)) indexLines.push(idxLine);
      }
    }
    if (!DRY) await fs.writeFile(indexPath, unique(indexLines).sort().join('\n') + '\n', 'utf8');
    console.log(`INDEX:   ${rel(indexPath)} updated`);
  }

  console.log(DRY ? '\n[Dry Run] 変更は未反映です。--dry-run=false で実行します。' : '\nDone.');
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
