// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by scripts/generate-plugin-loader.mjs
import type { PluginDefinition, PluginLoaderMap, PluginRegistryEntry } from './types.js';

export const pluginDefinitions: PluginDefinition[] = [
  {
    "nodeType": "basemap",
    "name": "BaseMap Plugin",
    "packageName": "@hierarchidb/basemap-plugin",
    "version": "1.0.0",
    "displayName": "BaseMap Plugin",
    "priority": 900,
    "dependencies": [
      "folder"
    ]
  },
  {
    "nodeType": "folder",
    "name": "Folder Plugin",
    "packageName": "@hierarchidb/folder-plugin",
    "version": "1.0.0",
    "displayName": "Folder",
    "priority": 1000,
    "dependencies": []
  },
  {
    "nodeType": "location",
    "name": "Location Plugin",
    "packageName": "@hierarchidb/location-plugin",
    "version": "0.1.0",
    "displayName": "Location",
    "priority": 40,
    "dependencies": []
  },
  {
    "nodeType": "route",
    "name": "Route Plugin",
    "packageName": "@hierarchidb/route-plugin",
    "version": "1.0.0",
    "displayName": "Route",
    "priority": 1000,
    "dependencies": [
      "shape"
    ]
  },
  {
    "nodeType": "shape",
    "name": "Shape Plugin",
    "packageName": "@hierarchidb/shape-plugin",
    "version": "0.1.0",
    "displayName": "Shape",
    "priority": 800,
    "dependencies": [
      "folder"
    ]
  },
  {
    "nodeType": "spreadsheet",
    "name": "Spreadsheet Plugin",
    "packageName": "@hierarchidb/spreadsheet-plugin",
    "version": "0.0.1",
    "displayName": "Spreadsheet",
    "priority": 600,
    "dependencies": [
      "folder"
    ]
  },
  {
    "nodeType": "styler",
    "name": "Styler Plugin",
    "packageName": "@hierarchidb/styler-plugin",
    "version": "1.0.0",
    "displayName": "Styler",
    "priority": 700,
    "dependencies": [
      "spreadsheet"
    ]
  },
  {
    "nodeType": "timeline",
    "name": "Timeline Plugin",
    "packageName": "@hierarchidb/timeline-plugin",
    "version": "0.0.1",
    "displayName": "Timeline",
    "priority": 1000,
    "dependencies": []
  }
];

export const pluginRegistry: PluginRegistryEntry[] = [
  {
    "nodeType": "basemap",
    "packageName": "@hierarchidb/basemap-plugin",
    "version": "1.0.0",
    "hasUI": true,
    "hasWorker": true,
    "hasDatabase": true,
    "hasCommon": false,
    "dependencies": [
      "folder"
    ],
    "manifest": null
  },
  {
    "nodeType": "folder",
    "packageName": "@hierarchidb/folder-plugin",
    "version": "1.0.0",
    "hasUI": true,
    "hasWorker": true,
    "hasDatabase": false,
    "hasCommon": false,
    "dependencies": [],
    "manifest": {
      "id": "@hierarchidb/folder-plugin",
      "name": "Folder Plugin",
      "displayName": "Folder",
      "nodeType": "folder",
      "version": "1.0.0",
      "description": "Basic folder plugin for HierarchiDB UI layer",
      "priority": 1000,
      "dependencies": [],
      "icon": {
        "mui": "Folder",
        "emoji": "📁",
        "color": "#c0eeff"
      },
      "category": "core",
      "schema": {
        "fields": [
          {
            "name": "name",
            "type": "string",
            "required": true
          },
          {
            "name": "description",
            "type": "string",
            "required": false
          }
        ]
      },
      "capabilities": {
        "canHaveChildren": true,
        "canBeRoot": true,
        "canBeDeleted": true,
        "canBeRenamed": true,
        "canBeMoved": true,
        "canBeCopied": true
      }
    }
  },
  {
    "nodeType": "location",
    "packageName": "@hierarchidb/location-plugin",
    "version": "0.1.0",
    "hasUI": true,
    "hasWorker": true,
    "hasDatabase": false,
    "hasCommon": false,
    "dependencies": [],
    "manifest": {
      "id": "@hierarchidb/location-plugin",
      "name": "Location Plugin",
      "displayName": "Location",
      "nodeType": "location",
      "version": "0.1.0",
      "description": "Geographic location nodes with Shape integration",
      "priority": 40,
      "dependencies": [],
      "icon": {
        "mui": "LocationOn",
        "emoji": "📍",
        "color": "#a3b030"
      },
      "category": {
        "menuGroup": "document",
        "createOrder": 40,
        "treeId": "*"
      },
      "capabilities": {
        "workingCopy": true,
        "batch": true,
        "visualization": true
      }
    }
  },
  {
    "nodeType": "route",
    "packageName": "@hierarchidb/route-plugin",
    "version": "1.0.0",
    "hasUI": true,
    "hasWorker": true,
    "hasDatabase": true,
    "hasCommon": false,
    "dependencies": [
      "shape"
    ],
    "manifest": {
      "id": "@hierarchidb/route-plugin",
      "name": "Route Plugin",
      "displayName": "Route",
      "nodeType": "route",
      "version": "1.0.0",
      "description": "Route management plugin extending Shape plugin for HierarchiDB",
      "extends": "shape",
      "dependencies": [
        "shape"
      ],
      "icon": {
        "mui": "Route",
        "emoji": "〰️",
        "color": "#a3b030"
      }
    }
  },
  {
    "nodeType": "shape",
    "packageName": "@hierarchidb/shape-plugin",
    "version": "0.1.0",
    "hasUI": true,
    "hasWorker": true,
    "hasDatabase": false,
    "hasCommon": false,
    "dependencies": [
      "folder"
    ],
    "manifest": {
      "id": "@hierarchidb/shape-plugin",
      "name": "Shape Plugin",
      "displayName": "Shape",
      "nodeType": "shape",
      "version": "0.1.0",
      "description": "Geographic shape data management plugin for HierarchiDB",
      "extends": "folder",
      "priority": 800,
      "dependencies": [
        "folder"
      ],
      "icon": {
        "mui": "Hexagon",
        "emoji": "♦️",
        "color": "#a3b030"
      },
      "category": "geographic",
      "schema": {
        "inherits": "folder",
        "fields": [
          {
            "name": "dataSourceName",
            "type": "string",
            "required": true
          },
          {
            "name": "selectedCountries",
            "type": "array",
            "required": true
          },
          {
            "name": "selectedAdminLevels",
            "type": "array",
            "required": true
          },
          {
            "name": "licenseAgreement",
            "type": "boolean",
            "required": true
          }
        ]
      },
      "capabilities": {
        "canHaveChildren": false,
        "canBeRoot": false,
        "canBeDeleted": true,
        "canBeRenamed": true,
        "canBeMoved": true,
        "canBeCopied": false,
        "supportsBatchProcessing": true
      }
    }
  },
  {
    "nodeType": "spreadsheet",
    "packageName": "@hierarchidb/spreadsheet-plugin",
    "version": "0.0.1",
    "hasUI": true,
    "hasWorker": true,
    "hasDatabase": true,
    "hasCommon": false,
    "dependencies": [
      "folder"
    ],
    "manifest": {
      "id": "@hierarchidb/spreadsheet-plugin",
      "name": "Spreadsheet Plugin",
      "displayName": "Spreadsheet",
      "nodeType": "spreadsheet",
      "version": "0.0.1",
      "description": "Spreadsheet plugin for HierarchiDB - extends folder plugin",
      "extends": "folder",
      "priority": 600,
      "dependencies": [
        "folder"
      ],
      "icon": {
        "mui": "Assessment",
        "emoji": "📈",
        "color": "#dcbc50"
      },
      "category": "data",
      "schema": {
        "inherits": "folder",
        "fields": [
          {
            "name": "spreadsheetData",
            "type": "object",
            "required": true
          },
          {
            "name": "formulas",
            "type": "object",
            "required": false
          }
        ]
      },
      "capabilities": {
        "canHaveChildren": false,
        "canBeRoot": false,
        "canBeDeleted": true,
        "canBeRenamed": true,
        "canBeMoved": true,
        "canBeCopied": true
      }
    }
  },
  {
    "nodeType": "styler",
    "packageName": "@hierarchidb/styler-plugin",
    "version": "1.0.0",
    "hasUI": true,
    "hasWorker": true,
    "hasDatabase": false,
    "hasCommon": false,
    "dependencies": [
      "spreadsheet"
    ],
    "manifest": {
      "id": "@hierarchidb/styler-plugin",
      "name": "Styler Plugin",
      "displayName": "Styler",
      "nodeType": "styler",
      "version": "1.0.0",
      "description": "Styler Plugin for HierarchiDB - Dynamic styling for map visualizations",
      "extends": "spreadsheet",
      "priority": 700,
      "dependencies": [
        "@hierarchidb/spreadsheet-plugin"
      ],
      "icon": {
        "mui": "Palette",
        "emoji": "🎨",
        "color": "#dcbc50"
      },
      "category": "visualization",
      "schema": {
        "inherits": "folder",
        "fields": [
          {
            "name": "csvData",
            "type": "string",
            "required": true
          },
          {
            "name": "mappingConfig",
            "type": "object",
            "required": true
          }
        ]
      },
      "capabilities": {
        "canHaveChildren": false,
        "canBeRoot": false,
        "canBeDeleted": true,
        "canBeRenamed": true,
        "canBeMoved": true,
        "canBeCopied": true
      }
    }
  },
  {
    "nodeType": "timeline",
    "packageName": "@hierarchidb/timeline-plugin",
    "version": "0.0.1",
    "hasUI": true,
    "hasWorker": true,
    "hasDatabase": false,
    "hasCommon": false,
    "dependencies": [],
    "manifest": {
      "id": "@hierarchidb/timeline-plugin",
      "name": "Timeline Plugin",
      "displayName": "Timeline",
      "nodeType": "timeline",
      "version": "0.0.1",
      "description": "Timeline plugin scaffold for HierarchiDB (new design)",
      "icon": {
        "mui": "Timeline",
        "emoji": "🕒",
        "color": "#8a7cbf"
      }
    }
  }
];

export const pluginMapUI: PluginLoaderMap = {
  'basemap': () => import('@hierarchidb/basemap-plugin/ui'),
  'folder': () => import('@hierarchidb/folder-plugin/ui'),
  'location': () => import('@hierarchidb/location-plugin/ui'),
  'route': () => import('@hierarchidb/route-plugin/ui'),
  'shape': () => import('@hierarchidb/shape-plugin/ui'),
  'spreadsheet': () => import('@hierarchidb/spreadsheet-plugin/ui'),
  'styler': () => import('@hierarchidb/styler-plugin/ui'),
  'timeline': () => import('@hierarchidb/timeline-plugin/ui'),
};

export const pluginMapWorker: PluginLoaderMap = {
  'basemap': () => import('@hierarchidb/basemap-plugin/worker'),
  'folder': () => import('@hierarchidb/folder-plugin/worker'),
  'location': () => import('@hierarchidb/location-plugin/worker'),
  'route': () => import('@hierarchidb/route-plugin/worker'),
  'shape': () => import('@hierarchidb/shape-plugin/worker'),
  'spreadsheet': () => import('@hierarchidb/spreadsheet-plugin/worker'),
  'styler': () => import('@hierarchidb/styler-plugin/worker'),
  'timeline': () => import('@hierarchidb/timeline-plugin/worker'),
};
