import { createTsupConfig } from '../../../../tsup.base.config.js';

export default createTsupConfig({
  external: [
    '@emotion/react',
    '@emotion/react/*',
    '@emotion/styled',
    '@emotion/styled/*',
    '@hierarchidb/common-types',
    '@hierarchidb/common-types/*',
    '@hierarchidb/components',
    '@hierarchidb/components/*',
    '@hierarchidb/ui-i18n',
    '@hierarchidb/ui-i18n/*',
    '@hierarchidb/ui-theme',
    '@hierarchidb/ui-theme/*',
    '@hierarchidb/ui-treeconsole-breadcrumb',
    '@hierarchidb/ui-treeconsole-breadcrumb/*',
    '@mui/icons-material',
    '@mui/icons-material/*',
    '@mui/material',
    '@mui/material/*',
    '@tanstack/react-router',
    '@tanstack/react-router/*',
    '@tanstack/react-table',
    '@tanstack/react-table/*',
    '@tanstack/react-virtual',
    '@tanstack/react-virtual/*',
    'comlink',
    'jotai',
    'react',
    'react-dom',
  ],});
