import { defineConfig } from 'vitest/config';
import path from 'path';

export default defineConfig({
  test: {
    environment: 'jsdom',
    globals: true,
    setupFiles: ['./src/ui/components/__tests__/setup.ts'],
    pool: 'threads',
    maxThreads: 1,
    minThreads: 1,
    coverage: {
      provider: 'v8',
      reportsDirectory: 'coverage',
      reporter: ['text', 'html', 'lcov'],
      all: true,
      include: ['src/**/*.{ts,tsx}'],
      exclude: ['**/*.test.{ts,tsx}', '**/__tests__/**', '**/*.stories.{ts,tsx}', '**/dist/**'],
    },
  },
  resolve: {
    alias: {
      '~': path.resolve(__dirname, 'src'),
      '@hierarchidb/util': path.resolve(__dirname, '../../packages/util/src/index.ts'),
      '@hierarchidb/download': path.resolve(__dirname, '../../packages/features/download/src/index.ts'),
      '@hierarchidb/runtime-client': path.resolve(__dirname, '../../packages/runtime/client/src/index.ts'),
      '@hierarchidb/basemap-plugin/icon': path.resolve(__dirname, 'src/ui/components/__tests__/__mocks__/BasemapPluginIcon.ts'),
      '@hierarchidb/folder-plugin/icon': path.resolve(__dirname, 'src/ui/components/__tests__/__mocks__/BasemapPluginIcon.ts'),
      '@hierarchidb/linker-plugin/icon': path.resolve(__dirname, 'src/ui/components/__tests__/__mocks__/BasemapPluginIcon.ts'),
      '@hierarchidb/location-plugin/icon': path.resolve(__dirname, 'src/ui/components/__tests__/__mocks__/BasemapPluginIcon.ts'),
      '@hierarchidb/resolver-plugin/icon': path.resolve(__dirname, 'src/ui/components/__tests__/__mocks__/BasemapPluginIcon.ts'),
      '@hierarchidb/route-plugin/icon': path.resolve(__dirname, 'src/ui/components/__tests__/__mocks__/BasemapPluginIcon.ts'),
      '@hierarchidb/shape-plugin/icon': path.resolve(__dirname, 'src/ui/components/__tests__/__mocks__/BasemapPluginIcon.ts'),
      '@hierarchidb/spreadsheet-plugin/icon': path.resolve(__dirname, 'src/ui/components/__tests__/__mocks__/BasemapPluginIcon.ts'),
      '@hierarchidb/styler-plugin/icon': path.resolve(__dirname, 'src/ui/components/__tests__/__mocks__/BasemapPluginIcon.ts'),
      '@hierarchidb/timeline-plugin/icon': path.resolve(__dirname, 'src/ui/components/__tests__/__mocks__/BasemapPluginIcon.ts'),
      '@hierarchidb/basemap-plugin': path.resolve(__dirname, 'src/ui/components/__tests__/__mocks__/pluginModuleStub.ts'),
      '@hierarchidb/folder-plugin': path.resolve(__dirname, 'src/ui/components/__tests__/__mocks__/pluginModuleStub.ts'),
      '@hierarchidb/linker-plugin': path.resolve(__dirname, 'src/ui/components/__tests__/__mocks__/pluginModuleStub.ts'),
      '@hierarchidb/location-plugin': path.resolve(__dirname, 'src/ui/components/__tests__/__mocks__/pluginModuleStub.ts'),
      '@hierarchidb/resolver-plugin': path.resolve(__dirname, 'src/ui/components/__tests__/__mocks__/pluginModuleStub.ts'),
      '@hierarchidb/route-plugin': path.resolve(__dirname, 'src/ui/components/__tests__/__mocks__/pluginModuleStub.ts'),
      '@hierarchidb/shape-plugin': path.resolve(__dirname, 'src/ui/components/__tests__/__mocks__/pluginModuleStub.ts'),
      '@hierarchidb/spreadsheet-plugin': path.resolve(__dirname, 'src/ui/components/__tests__/__mocks__/pluginModuleStub.ts'),
      '@hierarchidb/styler-plugin': path.resolve(__dirname, 'src/ui/components/__tests__/__mocks__/pluginModuleStub.ts'),
      '@hierarchidb/timeline-plugin': path.resolve(__dirname, 'src/ui/components/__tests__/__mocks__/pluginModuleStub.ts'),
      '@hierarchidb/plugin-registry/dist/registry.js': path.resolve(__dirname, 'src/ui/components/__tests__/__mocks__/pluginRegistryStub.ts'),
    },
  },
});
