// Minimal type shims for packages that don't have proper exports
// Most types are now imported from actual packages


// Vite virtual modules generated by @hierarchidb/tools-vite-plugin-package-reader
declare module 'virtual:plugin-definitions' {
  interface VMPluginDefinition {
    name: string;
    version: string;
    packageName: string;
    nodeType: string;
    priority: number;
    plugin?: any;
    config?: any;
  }
  const pluginDefinitions: VMPluginDefinition[];
  export default pluginDefinitions;
}

declare module 'virtual:plugin-map' {
  export const pluginMap: Record<string, () => Promise<unknown>>;
  export default pluginMap;
}

// Workspace UI packages without published types (temporary shims)
declare module '@hierarchidb/ui-treeconsole-base' {
  export type TreeConsolePanelProps = any;
  export type TreeNodeData = any;
  export type TreeTableColumn = any;
  export const TreeConsolePanel: any;
}
declare module '@hierarchidb/ui-usermenu' {
  const Default: any;
  export default Default;
  export const UserLoginButton: any;
}
declare module '@hierarchidb/ui-theme' {
  const Default: any;
  export default Default;
  export const ThemeProvider: any;
  export const createAppTheme: any;
}
declare module '@hierarchidb/ui-base-dialog' {
  const Default: any;
  export default Default;
  export const FullScreenDialog: any;
}

// Runtime worker bootstrap virtuals (temporary until package exports are aligned)
declare module '@hierarchidb/runtime-worker-worker' {
  const Default: any;
  export default Default;
  export const WorkerService: any;
  export const Bootstrap: any;
}
declare module '@hierarchidb/runtime-worker-worker-bootstrap' {
  const Default: any;
  export default Default;
  export const WorkerInitializationChannel: any;
  export const WorkerInitializationReporter: any;
}
declare module '@hierarchidb/runtime-worker-worker-init-notifier' {
  const Default: any;
  export default Default;
  export const WorkerInitializationReporter: any;
}
declare module '@hierarchidb/runtime-worker-worker/1-bootstrap/WorkerBootstrap' {
  export const WorkerBootstrap: any;
  export default WorkerBootstrap;
}

// Other external packages lacking types in this workspace
declare module 'maplibre-gl' {
  const Default: any;
  export default Default;
  export class Map {}
}
declare module '@tanstack/provider-query' {
  const Default: any;
  export default Default;
  export function useQuery(...args: any[]): any;
}
declare module 'react-hook-geolocation' { const useGeolocation: any; export default useGeolocation; export { useGeolocation }; }
