// Minimal type shims for packages that don't have proper exports
// Most types are now imported from actual packages


// Vite virtual modules generated by @hierarchidb/tools-vite-plugin-package-reader
declare module 'virtual:plugin-definitions' {
  interface VMPluginDefinition {
    name: string;
    version: string;
    packageName: string;
    nodeType: string;
    priority: number;
    plugin?: any;
    config?: any;
  }

  const pluginDefinitions: VMPluginDefinition[];
  export default pluginDefinitions;
}

// legacy virtual:plugin-map removed; use virtual:plugin-registry-*

//  Removed: UI and worker package shims replaced by real package types

// Provide minimal types for runtime-worker-bootstrap if TS cannot resolve declarations
declare module '@hierarchidb/runtime-worker-bootstrap' {
  export type WorkerInitMessageType =
    | 'INIT_REQUEST'
    | 'INIT_COMPLETE'
    | 'INIT_ERROR'
    | 'INIT_PROGRESS'
    | 'PING'
    | 'PING_RESPONSE';

  export interface WorkerInitConfig {
    worker: Worker;
    timeout?: number;
    debug?: boolean;
  }

  export interface InitializationResult {
    success: boolean;
    duration?: number;
    error?: Error;
  }

  export interface InitializationStep {
    name: string;
    weight: number;
  }

  export class WorkerInitializationReporter {
    constructor(steps?: InitializationStep[], debug?: boolean);

    reportStepProgress(message: string, progress: number): void;

    reportComplete(): void;

    reportError(message: string): void;
  }

  export class WorkerInitializationChannel {
    constructor();

    waitForInitialization(config: WorkerInitConfig): Promise<InitializationResult>;

    ping(): Promise<boolean>;

    dispose(): void;
  }
}

// Minimal shims for UI packages when dist-only type resolution is enforced
declare module '@hierarchidb/ui-icon' {
  export function getMuiIconComponent(name?: string, emoji?: string): any;
  export function getMuiIconWithColor(name?: string, emoji?: string, color?: string): any;
  export function setGlobalMuiIconMap(map: Record<string, any>): void;
  export function prefetchMuiIcons(names: Array<string | undefined | null>): Promise<void>;
}

declare module '@hierarchidb/ui-treeconsole-breadcrumb' {
  export const NodeTypeIcon: any;
  export const TreeConsoleBreadcrumb: any;
  export type BreadcrumbNode = any;
}

// Minimal shim for base TreeConsole components and types
declare module '@hierarchidb/ui-treeconsole-base' {
  export interface TreeNodeData {
    id: string;
    name: string;
    nodeType: string;
    description?: string;
    createdAt?: number;
    updatedAt?: number;
    hasChildren?: boolean;
    [key: string]: any;
  }
  export interface TreeTableColumn<T = TreeNodeData> {
    id: string;
    label: string;
    width?: number;
    sortable?: boolean;
    render?: (value: unknown, node: T) => any;
  }
  export interface TreeConsolePanelProps {
    [key: string]: any;
  }
  export const TreeConsolePanel: any;
}

// Vite virtual module generated by app/vite-plugin-mui-icons.ts
declare module 'virtual:mui-icon-map' {
  export const iconMap: Record<string, any>;
  export default iconMap;
}

declare module 'virtual:plugin-registry-services' {
  // Known service module types per nodeType
  type BasemapServices = typeof import('@hierarchidb/basemap-plugin/database');
  type ResolverServices = typeof import('@hierarchidb/resolver-plugin/database');
  type SpreadsheetServices = typeof import('@hierarchidb/spreadsheet-plugin/database');
  type ShapeServices = typeof import('@hierarchidb/shape-plugin/services');
  type RouteServices = typeof import('@hierarchidb/route-plugin/database');
  // Fallback for plugins without explicit services
  type UnknownMod = Record<string, unknown>;
  export const pluginServices: {
    basemap: () => Promise<BasemapServices>;
    resolver: () => Promise<ResolverServices>;
    spreadsheet: () => Promise<SpreadsheetServices>;
    shape: () => Promise<ShapeServices>;
    route: () => Promise<RouteServices>;
    [nodeType: string]: () => Promise<unknown>;
  };
}

declare module 'virtual:plugin-registry-worker' {
  export const pluginMapWorker: Record<string, () => Promise<unknown>>;
}

declare module 'virtual:plugin-registry-ui' {
  export const pluginMapUI: Record<string, () => Promise<unknown>>;
}

// Minimal shim for folder-plugin top-level helper used at app bootstrap
declare module '@hierarchidb/folder-plugin' {
  export function initializeDefaultNodeDialogExtensions(): Promise<void>;
}

declare module '@hierarchidb/ui-theme' {
  export type ThemeMode = 'light' | 'dark' | 'system';
  export function createAppTheme(mode: any): any;
  export function useThemeMode(): { actualTheme: any; setMode: (m: ThemeMode) => void };
  export function getStoredThemeMode(): ThemeMode | null;
  export const ThemeProvider: any;
}

// Minimal shim for ui-treeconsole-toolbar until full d.ts is available
declare module '@hierarchidb/ui-treeconsole-toolbar' {
  export type TreeConsoleToolbarActionParams = any;
  export const TreeConsoleToolbar: any;
}

// Minimal shim for ui-auth until full d.ts is available
declare module '@hierarchidb/ui-auth' {
  export const SimpleBFFAuthProvider: any;
  export function useSimpleBFFAuth(): any;
  export function useAuth(): any;
  export const BFFAuthService: any;
  export const LoginForm: any;
}

// Exports subpath shim for TS4.x (remove after TS5 migration or when nodenext is adopted)
declare module '@hierarchidb/resolver-plugin/database' {
  const mod: any;
  export = mod;
}
declare module '@hierarchidb/spreadsheet-plugin/database' {
  const mod: any;
  export = mod;
}
declare module '@hierarchidb/route-plugin/database' {
  const mod: any;
  export = mod;
}
declare module '@hierarchidb/shape-plugin/services' {
  const mod: any;
  export = mod;
}
declare module '@hierarchidb/location-plugin/services' {
  const mod: any;
  export = mod;
}
declare module '@hierarchidb/styler-plugin/services' {
  const mod: any;
  export = mod;
}
declare module '@hierarchidb/timeline-plugin/services' {
  const mod: any;
  export = mod;
}
declare module '@hierarchidb/linker-plugin/services' {
  const mod: any;
  export = mod;
}
