// Minimal type shims for packages that don't have proper exports
// Most types are now imported from actual packages


// Vite virtual modules generated by @hierarchidb/tools-vite-plugin-package-reader
declare module 'virtual:plugin-definitions' {
  interface VMPluginDefinition {
    name: string;
    version: string;
    packageName: string;
    nodeType: string;
    priority: number;
    plugin?: any;
    config?: any;
  }
  const pluginDefinitions: VMPluginDefinition[];
  export default pluginDefinitions;
}

declare module 'virtual:plugin-map' {
  export const pluginMap: Record<string, () => Promise<unknown>>;
  export default pluginMap;
}

// Removed: UI and worker package shims — replaced by real package types

// Provide minimal types for runtime-worker-bootstrap if TS cannot resolve declarations
declare module '@hierarchidb/runtime-worker-bootstrap' {
  export class WorkerInitializationReporter {
    reportStepProgress(message: string, progress: number): void;
    reportComplete(): void;
    reportError(message: string): void;
  }
  export class WorkerInitializationChannel {
    constructor(worker: Worker, opts?: { timeout?: number; debug?: boolean });
    on(event: 'progress' | 'complete' | 'error', cb: (e: any) => void): void;
    waitForInitialization(): Promise<{ success: boolean; error?: string }>;
    destroy(): void;
  }
}
