import { createTsupConfig } from '../../tsup.base.config';

export default createTsupConfig({
  entry: {
    'index': 'src/index.ts',
    'database/index': 'src/services/database/index.ts',
    'worker/index': 'src/worker/factory/index.ts',
    'ui/index': 'src/ui/index.ts',
  },
  dts: {
    entry: {
      'index': 'src/index.ts',
      'database/index': 'src/services/database/index.ts',
      'worker/index': 'src/worker/factory/index.ts',
      'ui/index': 'src/ui/index.ts',
    },
  },
  external: [
    '@emotion/provider',
    '@emotion/styled',
    '@hierarchidb/auth-recovery',
    '@hierarchidb/auth-recovery/*',
    '@hierarchidb/common-api',
    '@hierarchidb/common-api/*',
    '@hierarchidb/common-types',
    '@hierarchidb/common-types/*',
    '@hierarchidb/folder-plugin',
    '@hierarchidb/folder-plugin/*',
    '@hierarchidb/plugin-types',
    '@hierarchidb/plugin-types/*',
    '@hierarchidb/plugin-ui-sdk',
    '@hierarchidb/plugin-ui-sdk/*',
    '@hierarchidb/runtime-basic-info',
    '@hierarchidb/runtime-basic-info/*',
    '@hierarchidb/runtime-plugin-dialog',
    '@hierarchidb/runtime-plugin-dialog/*',
    '@hierarchidb/runtime-ui-plugin-dialog',
    '@hierarchidb/runtime-worker',
    '@hierarchidb/runtime-worker/*',
    '@hierarchidb/tabular-source',
    '@hierarchidb/tabular-source/*',
    '@hierarchidb/tabular-store',
    '@hierarchidb/tabular-store/*',
    '@hierarchidb/ui-datasource',
    '@hierarchidb/ui-datasource/*',
    '@hierarchidb/ui-file',
    '@hierarchidb/ui-file/*',
    '@hierarchidb/ui-tabular-extract',
    '@hierarchidb/ui-tabular-extract/*',
    '@hierarchidb/util',
    '@hierarchidb/util/*',
    '@mui/icons-material',
    '@mui/icons-material/*',
    '@mui/material',
    '@mui/material/*',
    'i18next',
    'provider',
    'provider-dom',
    'provider-i18next',
    'react',
    'react-i18next',
  ],});
