import { createTsupConfig } from '../../tsup.base.config';

export default createTsupConfig({
  entry: {
    index: 'src/index.ts',
    'worker/index': 'src/worker/factory/index.ts',
    'ui/index': 'src/ui/index.ts',
    'database/index': 'src/services/database/index.ts',
  },
  dts: {
    entry: {
      'index': 'src/index.ts',
      'worker/index': 'src/worker/factory/index.ts',
      'ui/index': 'src/ui/index.ts',
      'database/index': 'src/services/database/index.ts',
    },
  },
  external: [
    '@emotion/react',
    '@emotion/react/*',
    '@emotion/styled',
    '@emotion/styled/*',
    '@hierarchidb/auth-recovery',
    '@hierarchidb/auth-recovery/*',
    '@hierarchidb/batch',
    '@hierarchidb/batch-types',
    '@hierarchidb/batch-types/*',
    '@hierarchidb/batch/*',
    '@hierarchidb/common-api',
    '@hierarchidb/common-api/*',
    '@hierarchidb/common-types',
    '@hierarchidb/common-types/*',
    '@hierarchidb/components',
    '@hierarchidb/components/*',
    '@hierarchidb/download',
    '@hierarchidb/download/*',
    '@hierarchidb/plugin-types',
    '@hierarchidb/plugin-types/*',
    '@hierarchidb/plugin-ui-sdk',
    '@hierarchidb/plugin-ui-sdk/*',
    '@hierarchidb/runtime-basic-info',
    '@hierarchidb/runtime-basic-info/*',
    '@hierarchidb/runtime-client',
    '@hierarchidb/runtime-client/*',
    '@hierarchidb/runtime-plugin-dialog',
    '@hierarchidb/runtime-plugin-dialog/*',
    '@hierarchidb/runtime-ui-plugin-dialog',
    '@hierarchidb/runtime-worker',
    '@hierarchidb/runtime-worker-factory',
    '@hierarchidb/runtime-worker/*',
    '@hierarchidb/tabular-store',
    '@hierarchidb/tabular-store/*',
    '@hierarchidb/ui-core',
    '@hierarchidb/ui-data-grid',
    '@hierarchidb/ui-data-grid/*',
    '@hierarchidb/ui-dialog',
    '@hierarchidb/ui-dialog/*',
    '@hierarchidb/util',
    '@hierarchidb/util/*',
    '@mui/icons-material',
    '@mui/icons-material/*',
    '@mui/material',
    '@mui/material/*',
    'react',
    'react-dom',
  ],});
