import type { 
  PackageJson,
  PackageDetectionStrategy,
  TransformPipelineOptions,
  VirtualModuleGenerator,
  VitePluginPackageReaderOptions
} from '../types';
import { RegexStrategy } from '../strategies';
import { DependencyResolver } from '../pipeline/DependencyResolver';

/**
 * HierarchiDB プラグイン定義
 */
export interface PluginDefinition {
  name: string;
  version: string;
  packageName: string;
  nodeType: string;
  priority: number;
  config?: any;
  dependencies?: string[];
}

/**
 * HierarchiDB戦略のオプション
 */
export interface HierarchiDBStrategyOptions {
  pattern?: RegExp;
  priorityPlugin?: string;
  extractPluginConfig?: boolean;
  priorityBoost?: number;
}

/**
 * HierarchiDB用の検出戦略を作成
 */
export function createHierarchiDBStrategy(
  options: HierarchiDBStrategyOptions = {}
): PackageDetectionStrategy {
  const pattern = options.pattern || /@hierarchidb\/node-type-.*-plugin$/;
  const priorityPlugin = options.priorityPlugin || 'folder';
  const priorityBoost = options.priorityBoost || 100;

  const strategy = new RegexStrategy({
    name: 'hierarchidb-plugin',
    pattern,
    metadataExtractor: (packageJson: PackageJson) => {
      const metadata: Record<string, any> = {};
      
      // node-typeを抽出
      const match = packageJson.name.match(/node-type-(.+)-plugin$/);
      if (match) {
        metadata.nodeType = match[1];
      }

      // hierarchidb設定を抽出
      if (options.extractPluginConfig && packageJson.hierarchidb?.plugin) {
        metadata.pluginConfig = packageJson.hierarchidb.plugin;
      }

      return metadata;
    },
  });
  
  // testメソッドをオーバーライド
  const originalTest = strategy.test.bind(strategy);
  strategy.test = function(packageName: string, packageJson: PackageJson): boolean {
    if (!originalTest(packageName, packageJson)) {
      return false;
    }

    // 優先度設定
    let priority = 1000;
    if (packageName.includes(priorityPlugin)) {
      priority = 1; // 最優先
    } else {
      // アルファベット順
      const match = packageName.match(/node-type-(.+)-plugin$/);
      if (match && match[1]) {
        priority = match[1].charCodeAt(0) + priorityBoost;
      }
    }
    
    packageJson.__priority = priority;
    
    return true;
  };
  
  return strategy;
}

/**
 * PluginDefinition生成パイプラインを作成
 */
export function createPluginDefinitionPipeline(): TransformPipelineOptions<PluginDefinition[]> {
  return {
    transform: (packages: Map<string, PackageJson>) => {
      const definitions: PluginDefinition[] = [];
      
      for (const [name, pkg] of packages) {
        const nodeType = pkg.__metadata?.nodeType || 
          name.replace('@hierarchidb/', '').replace('-plugin', '');
        
        definitions.push({
          name: nodeType,
          version: pkg.version,
          packageName: name,
          nodeType,
          priority: pkg.__priority || 1000,
          config: pkg.__metadata?.pluginConfig || pkg.hierarchidb?.plugin,
          dependencies: DependencyResolver.getDependencies(pkg),
        });
      }
      
      // 定義をpriority順にソート
      return definitions.sort((a, b) => a.priority - b.priority);
    },
  };
}

/**
 * Virtual Module生成器を作成
 */
export function createPluginVirtualModule(): VirtualModuleGenerator<PluginDefinition[]> {
  return {
    moduleId: 'plugin-definitions',
    
    generate: (definitions: PluginDefinition[]) => {
      const imports: string[] = [];
      const registrations: string[] = [];
      
      for (const def of definitions) {
        const importName = `${def.nodeType}Plugin`;
        imports.push(
          `import ${importName} from '${def.packageName}';`
        );
        
        registrations.push(`{
    name: '${def.name}',
    version: '${def.version}',
    packageName: '${def.packageName}',
    nodeType: '${def.nodeType}',
    priority: ${def.priority},
    plugin: ${importName},
    config: ${JSON.stringify(def.config || {}, null, 2).split('\n').join('\n    ')}
  }`);
      }
      
      return `// Auto-generated by @hierarchidb/tools-vite-plugin-package-reader
${imports.join('\n')}

export const pluginDefinitions = [
  ${registrations.join(',\n  ')}
];

export default pluginDefinitions;
`;
    },
    
    generateTypes: (definitions: PluginDefinition[]) => {
      const nodeTypes = definitions.map(d => `'${d.nodeType}'`).join(' | ');
      
      return `
export interface PluginDefinition {
  name: string;
  version: string;
  packageName: string;
  nodeType: string;
  priority: number;
  plugin: any;
  config?: any;
}

export type NodeType = ${nodeTypes};

export const pluginDefinitions: PluginDefinition[];
export default pluginDefinitions;
`;
    },
  };
}

/**
 * HierarchiDB用のプリセット設定
 */
export function hierarchiDBPreset(
  options: Partial<HierarchiDBStrategyOptions> = {}
): VitePluginPackageReaderOptions<PluginDefinition[]> {
  return {
    strategies: [createHierarchiDBStrategy(options)],
    pipeline: createPluginDefinitionPipeline(),
    virtualModules: [createPluginVirtualModule()],
    monorepo: {
      packages: ['packages/node-type/*'],
      resolveWorkspace: true,
      usePnpmWorkspace: true,
    },
    cache: true,
    watch: true,
    logger: {
      level: 'info',
      prefix: '[HierarchiDB]',
    },
    hooks: {
      afterDetection: async (packages) => {
        console.log(`Found ${packages.size} HierarchiDB plugins`);
      },
    },
  };
}

/**
 * 複数のVirtual Moduleを生成するプリセット
 */
export function hierarchiDBMultiModulePreset(
  options: Partial<HierarchiDBStrategyOptions> = {}
): VitePluginPackageReaderOptions<PluginDefinition[]> {
  const base = hierarchiDBPreset(options);
  
  // 追加のVirtual Modules
  const pluginMapModule: VirtualModuleGenerator<PluginDefinition[]> = {
    moduleId: 'plugin-map',
    generate: (definitions) => {
      const entries = definitions.map(d => 
        `  '${d.nodeType}': () => import('${d.packageName}')`
      );
      
      return `// Auto-generated plugin map
export const pluginMap = {
${entries.join(',\n')}
};

export default pluginMap;
`;
    },
  };
  
  const pluginTypesModule: VirtualModuleGenerator<PluginDefinition[]> = {
    moduleId: 'plugin-types',
    generate: (definitions) => {
      const types = definitions.map(d => `  ${d.nodeType}: '${d.nodeType}'`);
      
      return `// Auto-generated plugin types
export const NodeTypes = {
${types.join(',\n')}
} as const;

export type NodeType = keyof typeof NodeTypes;
`;
    },
  };
  
  return {
    ...base,
    virtualModules: [
      createPluginVirtualModule(),
      pluginMapModule,
      pluginTypesModule,
    ],
  };
}