import * as fs from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parseCsv } from "./csv.js";

type GeoboundariesRecord = Record<string, unknown>;
type GeoboundariesLevel = 0 | 1 | 2;
type GeoboundariesPayload = GeoboundariesRecord | GeoboundariesRecord[];

const GEOBOUNDARIES_API_BY_LEVEL: Record<GeoboundariesLevel, string> = {
  0: "https://www.geoboundaries.org/api/current/gbOpen/ALL/ADM0/",
  1: "https://www.geoboundaries.org/api/current/gbOpen/ALL/ADM1/",
  2: "https://www.geoboundaries.org/api/current/gbOpen/ALL/ADM2/",
};

const OUTPUT_PATH = resolve(
  dirname(fileURLToPath(import.meta.url)),
  "../../../..",
  "app",
  "src",
  "features",
  "shape",
  "generated",
  "geoboundaries-shape-presets.generated.ts",
);
const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../../../..");
const LOCAL_ISO3166_CSV_CANDIDATES = [
  resolve(process.cwd(), "app/public/iso3166-2-level1.csv"),
  resolve(REPO_ROOT, "app/public/iso3166-2-level1.csv"),
];

const isFile = async (path: string): Promise<boolean> => {
  try {
    const stat = await fs.stat(path);
    return stat.isFile();
  } catch {
    return false;
  }
};

const resolveIso3166CsvPath = async (): Promise<string | null> => {
  for (const candidate of LOCAL_ISO3166_CSV_CANDIDATES) {
    if (await isFile(candidate)) {
      return candidate;
    }
  }
  return null;
};

const loadIso3166Map = async (): Promise<Map<string, string>> => {
  const csvPath = await resolveIso3166CsvPath();
  if (!csvPath) {
    return new Map<string, string>();
  }
  const csvText = await fs.readFile(csvPath, "utf8");
  const rows = parseCsv(csvText);
  const map = new Map<string, string>();
  for (const row of rows) {
    const alpha3 = row.alpha3.trim().toUpperCase();
    const alpha2 = row.alpha2.trim().toUpperCase();
    if (alpha3.length === 3 && alpha2.length === 2) {
      map.set(alpha3, alpha2);
    }
  }
  return map;
};

const isString = (value: unknown): value is string => typeof value === "string";

const readFirstString = (record: GeoboundariesRecord, keys: readonly string[]): string | null => {
  for (const key of keys) {
    const raw = record[key];
    if (isString(raw)) {
      const trimmed = raw.trim();
      if (trimmed) return trimmed;
    }
  }
  return null;
};

const readGeoboundariesPayload = (payload: unknown): GeoboundariesRecord[] => {
  if (Array.isArray(payload)) return payload as GeoboundariesRecord[];
  if (payload && typeof payload === "object") {
    const directData = (payload as GeoboundariesPayload as { data?: unknown }).data;
    if (Array.isArray(directData)) return directData as GeoboundariesRecord[];
  }
  return [];
};

const extractIso2 = (
  record: GeoboundariesRecord,
  iso3ToIso2: Map<string, string>,
): string | null => {
  const raw = readFirstString(record, [
    "boundaryISO",
    "iso3",
    "ISO3",
    "shapeISO",
    "shapeISO3",
    "boundaryISO3",
    "countryCode",
    "countryISO",
    "country_code",
    "iso",
  ]);
  if (!raw) return null;
  const [first = ""] = raw.split(/[,\s;/|]/);
  const upper = first.toUpperCase();
  if (/^[A-Z]{2}$/.test(upper)) return upper;
  if (/^[A-Z]{3}$/.test(upper)) {
    return iso3ToIso2.get(upper) ?? null;
  }
  return null;
};

const loadGeoboundariesCountries = async (
  level: GeoboundariesLevel,
  iso3ToIso2: Map<string, string>,
): Promise<ReadonlySet<string>> => {
  const url = GEOBOUNDARIES_API_BY_LEVEL[level];
  const response = await fetch(url, { headers: { accept: "application/json" } });
  if (!response.ok) {
    throw new Error(`Failed to fetch geoboundaries level ${level}: ${response.status}`);
  }
  const payload = await response.json();
  const records = readGeoboundariesPayload(payload);
  const output = new Set<string>();
  for (const record of records) {
    const iso = extractIso2(record, iso3ToIso2);
    if (iso && /^[A-Z]{2}$/.test(iso)) {
      output.add(iso);
    }
  }
  return output;
};

const buildGeneratedPayload = async (): Promise<{
  level0: string[];
  level1: string[];
}> => {
  const iso3ToIso2 = await loadIso3166Map();

  const level0 = Array.from(await loadGeoboundariesCountries(0, iso3ToIso2)).sort();
  const level1 = Array.from(await loadGeoboundariesCountries(1, iso3ToIso2)).sort();
  return { level0, level1 };
};

const renderGeneratedFile = (level0: string[], level1: string[]): string =>
  `// generated by @hierarchidb/gen-iso3166-2
// This file is produced at build time. Do not edit manually.
export const GEOBOUNDARIES_COUNTRIES_BY_LEVEL = {
  level0: ${JSON.stringify(level0, null, 2)},
  level1: ${JSON.stringify(level1, null, 2)},
} as const;
`;

const writeGeneratedFile = async (level0: string[], level1: string[]) => {
  const directory = dirname(OUTPUT_PATH);
  await fs.mkdir(directory, { recursive: true });
  await fs.writeFile(OUTPUT_PATH, renderGeneratedFile(level0, level1), "utf8");
};

const isDirectRun = (() => {
  if (typeof process === "undefined" || typeof import.meta.url !== "string") return false;
  try {
    const current = new URL(import.meta.url);
    const entry = process.argv[1] ? new URL(`file://${process.argv[1]}`) : null;
    if (!entry) return false;
    return current.href === entry.href;
  } catch {
    return false;
  }
})();

const main = async () => {
  const data = await buildGeneratedPayload();
  await writeGeneratedFile(data.level0, data.level1);
};

if (isDirectRun) {
  void main().catch((error) => {
    console.error(error);
    process.exit(1);
  });
}

export { buildGeneratedPayload };
