import { createTsupConfig } from '../../../tsup.base.config.js';

export default createTsupConfig({
  external: [
    '@emotion/react',
    '@emotion/styled',
    '@hierarchidb/batch-types',
    '@hierarchidb/batch-types/*',
    '@hierarchidb/common-api',
    '@hierarchidb/common-api/*',
    '@hierarchidb/common-types',
    '@hierarchidb/common-types/*',
    '@hierarchidb/plugin-types',
    '@hierarchidb/plugin-types/*',
    '@hierarchidb/runtime-basic-info',
    '@hierarchidb/runtime-basic-info/*',
    '@hierarchidb/runtime-client',
    '@hierarchidb/runtime-client/*',
    '@hierarchidb/runtime-worker',
    '@hierarchidb/runtime-worker/*',
    '@hierarchidb/ui-core',
    '@hierarchidb/ui-dialog',
    '@hierarchidb/ui-dialog/*',
    '@hierarchidb/ui-icon',
    '@hierarchidb/ui-icon/*',
    '@mui/icons-material',
    '@mui/icons-material/*',
    '@mui/material',
    '@mui/material/*',
    '@tanstack/react-router',
    '@tanstack/react-router/*',
    'comlink',
    'jotai',
    'react',
    'react-dom',
  ],clean: false,
});
