import { createTsupConfig } from '../../tsup.base.config';

export default createTsupConfig({
  entry: {
    index: 'src/index.ts',
    'ui/index': 'src/ui/index.ts',
    'worker/index': 'src/worker/factory/index.ts',
    'database/index': 'src/services/database/index.ts',
  },
  external: [
    '@emotion/provider',
    '@emotion/react',
    '@emotion/react/*',
    '@emotion/styled',
    '@emotion/styled/*',
    '@hierarchidb/common-api',
    '@hierarchidb/common-api/*',
    '@hierarchidb/common-types',
    '@hierarchidb/common-types/*',
    '@hierarchidb/folder-plugin',
    '@hierarchidb/folder-plugin/*',
    '@hierarchidb/plugin-runtime-services',
    '@hierarchidb/plugin-runtime-services/*',
    '@hierarchidb/plugin-types',
    '@hierarchidb/plugin-types/*',
    '@hierarchidb/plugin-ui-sdk',
    '@hierarchidb/plugin-ui-sdk/*',
    '@hierarchidb/runtime-plugin-dialog',
    '@hierarchidb/runtime-plugin-dialog/*',
    '@hierarchidb/runtime-worker',
    '@hierarchidb/runtime-worker/*',
    '@hierarchidb/ui-data-grid',
    '@hierarchidb/ui-data-grid/*',
    '@hierarchidb/ui-map',
    '@hierarchidb/ui-map/*',
    '@hierarchidb/util',
    '@hierarchidb/util/*',
    '@mui/icons-material',
    '@mui/icons-material/*',
    '@mui/material',
    '@mui/material/*',
    'dexie',
    'provider',
    'provider-dom',
    'react',
  ],});
