import { resolveSpecifierExpression, resolveTargetSpecifier } from './entry-resolver.js';
import type { ManifestSummary, PluginSpecifierMode } from './types.js';

function indentJSON(value: unknown, indent: number): string {
  const json = JSON.stringify(value, null, 2);
  if (!json.includes('\n')) return json;
  const indentation = ' '.repeat(indent);
  return json.replace(/\n/g, `\n${indentation}`);
}

function formatModuleInfo(
  specifierExpr: string,
  options: { source?: string | null; exportName?: string } = {}
): string {
  const lines: string[] = ['{', `        specifier: ${specifierExpr},`];
  if (options.source) {
    lines.push(`        source: ${JSON.stringify(options.source)},`);
  }
  if (options.exportName) {
    lines.push(`        exportName: ${JSON.stringify(options.exportName)},`);
  }
  lines.push('      }');
  return lines.join('\n');
}

function hasWorkerModule(summary: ManifestSummary, mode: PluginSpecifierMode): boolean {
  if (!summary.hasWorker) return false;
  if (summary.workerSourceEntry) return true;
  return mode === 'dist-url' && Boolean(summary.workerDistEntry);
}

function formatModulesLiteral(summary: ManifestSummary, mode: PluginSpecifierMode): string {
  const entries: string[] = [];
  const rootSpecifier = resolveSpecifierExpression(
    summary.packageName,
    summary.rootDistEntry,
    mode
  );
  entries.push(`    root: ${formatModuleInfo(rootSpecifier)}`);

  if (summary.hasUI && (summary.uiSourceEntry || summary.uiDistEntry)) {
    const specExpr = resolveSpecifierExpression(
      `${summary.packageName}/ui`,
      summary.uiDistEntry,
      mode
    );
    entries.push(`    ui: ${formatModuleInfo(specExpr, { source: summary.uiSourceEntry })}`);
  }

  if (hasWorkerModule(summary, mode)) {
    const specExpr = resolveSpecifierExpression(
      `${summary.packageName}/worker`,
      summary.workerDistEntry,
      mode
    );
    entries.push(
      `    worker: ${formatModuleInfo(specExpr, { source: summary.workerSourceEntry })}`
    );
  }

  if (summary.hasDatabaseModule && (summary.databaseSourceEntry || summary.databaseDistEntry)) {
    const specExpr = resolveSpecifierExpression(
      `${summary.packageName}/database`,
      summary.databaseDistEntry,
      mode
    );
    entries.push(
      `    database: ${formatModuleInfo(specExpr, { source: summary.databaseSourceEntry })}`
    );
  }

  if (summary.hasCommon && (summary.commonSourceEntry || summary.commonDistEntry)) {
    const specExpr = resolveSpecifierExpression(
      `${summary.packageName}/common`,
      summary.commonDistEntry,
      mode
    );
    entries.push(
      `    common: ${formatModuleInfo(specExpr, { source: summary.commonSourceEntry })}`
    );
  }

  if (summary.iconComponent) {
    const icon = summary.iconComponent;
    const iconSpecExpr = resolveSpecifierExpression(icon.specifier, icon.distEntry ?? null, mode);
    entries.push(
      `    icon: ${formatModuleInfo(iconSpecExpr, { source: icon.sourceEntry, exportName: icon.exportName })}`
    );
  }

  return entries.length > 0
    ? `{
${entries.join(',\n')}
  }`
    : '{}';
}

export function generateRegistrySource(
  summaries: ManifestSummary[],
  mode: PluginSpecifierMode
): string {
  const entries = summaries
    .map((summary) => {
      const version = summary.manifest.version ?? summary.packageVersion;
      const dependenciesJSON = indentJSON(summary.dependencies, 6);
      const manifestJSON = indentJSON(summary.manifest ?? null, 6);
      const modulesLiteral = formatModulesLiteral(summary, mode);

      return `  {\n    nodeType: ${JSON.stringify(summary.nodeType)},\n    packageName: ${JSON.stringify(summary.packageName)},\n    version: ${JSON.stringify(version)},\n    dependencies: ${dependenciesJSON},\n    exports: ${JSON.stringify(summary.exportPaths)},\n    manifest: ${manifestJSON},\n    modules: ${modulesLiteral}\n  },`;
    })
    .join('\n');

  return `/* auto-generated by tools-build-scripts */\n/// <reference path="./registry.modules.d.ts" />\nimport type { PluginRegistryEntry } from '../src/types.js';\n\nexport const pluginRegistry: PluginRegistryEntry[] = [\n${entries}\n];\n`;
}

export function generatePluginDefinitionsSource(): string {
  return `/* auto-generated by tools-build-scripts */\nimport { pluginRegistry } from './registry.js';\nimport { derivePluginDefinitions } from '../src/derivations.js';\nimport type { PluginDefinition } from '../src/types.js';\n\nexport const pluginDefinitions: PluginDefinition[] = derivePluginDefinitions(pluginRegistry);\n`;
}

export function generateDerivationsSource(): string {
  return `/* auto-generated by tools-build-scripts */\nexport * from '../src/derivations.js';\n`;
}

export function generateUiLoadersSource(
  summaries: ManifestSummary[],
  mode: PluginSpecifierMode
): string {
  const entries = summaries
    .map((summary) => {
      if (!summary.hasUI || (!summary.uiSourceEntry && !summary.uiDistEntry)) {
        return null;
      }
      const specExpr = resolveSpecifierExpression(
        `${summary.packageName}/ui`,
        summary.uiDistEntry,
        mode
      );
      return `  ${JSON.stringify(summary.nodeType)}: async () => import(${specExpr}),`;
    })
    .filter((entry): entry is string => typeof entry === 'string' && entry.length > 0)
    .join('\n');

  const loaderBody = entries.length > 0 ? `{\n${entries}\n}` : '{}';

  const mapEntries = summaries
    .map((summary) => {
      if (!summary.hasUI || (!summary.uiSourceEntry && !summary.uiDistEntry)) {
        return null;
      }
      const specExpr = resolveSpecifierExpression(
        `${summary.packageName}/ui`,
        summary.uiDistEntry,
        mode
      );
      return `  ${JSON.stringify(summary.nodeType)}: ${specExpr},`;
    })
    .filter((entry): entry is string => typeof entry === 'string' && entry.length > 0)
    .join('\n');
  const mapBody = mapEntries.length > 0 ? `{\n${mapEntries}\n}` : '{}';
  return `/* auto-generated by tools-build-scripts */\n/// <reference path="./registry.modules.d.ts" />\n\nexport const pluginUiLoaders: Record<string, () => Promise<unknown>> = ${loaderBody};\nexport const pluginUiModuleMap: Record<string, string> = ${mapBody};\n`;
}

export function generateWorkerLoadersSource(
  summaries: ManifestSummary[],
  mode: PluginSpecifierMode
): string {
  const loaderEntries = summaries
    .map((summary) => {
      if (!hasWorkerModule(summary, mode)) {
        return null;
      }
      const specExpr = resolveSpecifierExpression(
        `${summary.packageName}/worker`,
        summary.workerDistEntry,
        mode
      );
      return `  ${JSON.stringify(summary.nodeType)}: async () => import(${specExpr}),`;
    })
    .filter((entry): entry is string => typeof entry === 'string' && entry.length > 0)
    .join('\n');

  const preloadEntries = summaries
    .map((summary) => {
      if (
        !hasWorkerModule(summary, mode) ||
        !summary.workerPreloadExports ||
        summary.workerPreloadExports.length === 0
      ) {
        return null;
      }
      const exportsJSON = JSON.stringify(summary.workerPreloadExports);
      return `  ${JSON.stringify(summary.nodeType)}: ${exportsJSON},`;
    })
    .filter((entry): entry is string => typeof entry === 'string' && entry.length > 0)
    .join('\n');

  const loaderBody = loaderEntries.length > 0 ? `{\n${loaderEntries}\n}` : '{}';
  const preloadBody = preloadEntries.length > 0 ? `{\n${preloadEntries}\n}` : '{}';

  return `/* auto-generated by tools-build-scripts */\n/// <reference path="./registry.modules.d.ts" />\n\nexport const pluginWorkerLoaders: Record<string, () => Promise<unknown>> = ${loaderBody};\nexport const pluginWorkerPreloads: Record<string, string[]> = ${preloadBody};\n`;
}

export function generateIconLoadersSource(summaries: ManifestSummary[]): string {
  const iconLoaderEntries = summaries
    .map((summary) => {
      const component = summary.iconComponent;
      if (!component) return null;
      const lines: string[] = [];
      lines.push(`  ${JSON.stringify(summary.nodeType)}: async () => {`);
      lines.push(`    const mod = await import('${component.specifier}');`);
      if (component.exportName) {
        lines.push(
          `    const componentExport = (mod as Record<string, unknown>)[${JSON.stringify(component.exportName)}];`
        );
        lines.push(
          `    if (!componentExport) { throw new Error('Plugin icon component export not found for ${summary.nodeType}'); }`
        );
        lines.push('    return componentExport;');
      } else {
        lines.push('    const resolved = (mod as { default?: unknown }).default ?? mod;');
        lines.push(
          `    if (!resolved) { throw new Error('Plugin icon component default export not found for ${summary.nodeType}'); }`
        );
        lines.push('    return resolved;');
      }
      lines.push('  },');
      return lines.join('\n');
    })
    .filter((entry): entry is string => typeof entry === 'string' && entry.length > 0)
    .join('\n');

  const loaderBody = iconLoaderEntries.length > 0 ? `{\n${iconLoaderEntries}\n}` : '{}';
  return `/* auto-generated by tools-build-scripts */\n/// <reference path="./registry.modules.d.ts" />\n\nexport const pluginIconLoaders: Record<string, () => Promise<unknown>> = ${loaderBody};\n`;
}

export function generateDatabaseLoadersSource(
  summaries: ManifestSummary[],
  mode: PluginSpecifierMode
): string {
  const databaseLoaderEntries = summaries
    .map((summary) => {
      const moduleSpecifier = summary.databaseModuleSpecifier;
      const hasLoader =
        summary.hasDatabaseModule &&
        typeof moduleSpecifier === 'string' &&
        moduleSpecifier.length > 0;
      const hasPrewarm = summary.hasDatabaseModule && summary.databasePrewarmTargets.length > 0;
      if (!hasLoader && !hasPrewarm) {
        return null;
      }
      const lines: string[] = [];
      lines.push(`  ${JSON.stringify(summary.nodeType)}: {`);
      if (hasLoader) {
        const moduleSpecifierExpr = resolveSpecifierExpression(
          moduleSpecifier,
          summary.databaseDistEntry,
          mode
        );
        lines.push(`    moduleSpecifier: ${moduleSpecifierExpr},`);
        lines.push('    async loader() {');
        lines.push(`      const mod = await import(${moduleSpecifierExpr});`);
        lines.push('      return mod;');
        lines.push('    },');
      }
      if (hasPrewarm) {
        lines.push('    prewarm: [');
        for (const target of summary.databasePrewarmTargets) {
          const targetSpecifierExpr = resolveTargetSpecifier(target.specifier, summary, mode);
          lines.push('      {');
          lines.push(`        specifier: ${targetSpecifierExpr},`);
          lines.push(`        exportName: ${JSON.stringify(target.exportName)},`);
          lines.push('        async load() {');
          lines.push(`          const mod = await import(${targetSpecifierExpr});`);
          lines.push('          return mod;');
          lines.push('        },');
          lines.push('      },');
        }
        lines.push('    ],');
      }
      lines.push('  },');
      return lines.join('\n');
    })
    .filter((entry): entry is string => typeof entry === 'string' && entry.length > 0)
    .join('\n');

  const loaderBody = databaseLoaderEntries.length > 0 ? `{\n${databaseLoaderEntries}\n}` : '{}';
  return `/* auto-generated by tools-build-scripts */\n/// <reference path="./registry.modules.d.ts" />\n\nexport const pluginDatabaseLoaders: Record<string, { moduleSpecifier?: string; loader?: () => Promise<unknown>; prewarm?: { specifier?: string; exportName: string; load: () => Promise<unknown> }[] }> = ${loaderBody};\n`;
}

export function generateModuleDeclarationSource(summaries: ManifestSummary[]): string {
  const seen = new Set<string>();
  const lines: string[] = ['/* auto-generated by tools-stage-scripts */', ''];

  const isValidIdentifier = (value: string): boolean => /^[$A-Z_][0-9A-Z_$]*$/i.test(value);

  for (const summary of summaries) {
    const uiSpecifier =
      summary.uiSourceEntry || summary.uiDistEntry ? `${summary.packageName}/ui` : null;
    if (uiSpecifier && !seen.has(uiSpecifier)) {
      seen.add(uiSpecifier);
      lines.push(`declare module '${uiSpecifier}' {`);
      lines.push('  const mod: Record<string, unknown>;');
      lines.push('  export default mod;');
      lines.push('}');
      lines.push('');
    }

    const workerSpecifier =
      summary.workerSourceEntry || summary.workerDistEntry ? `${summary.packageName}/worker` : null;
    if (workerSpecifier && !seen.has(workerSpecifier)) {
      seen.add(workerSpecifier);
      lines.push(`declare module '${workerSpecifier}' {`);
      lines.push('  const mod: Record<string, unknown>;');
      lines.push('  export default mod;');
      lines.push('}');
      lines.push('');
    }

    const icon = summary.iconComponent;
    if (icon && !seen.has(icon.specifier)) {
      seen.add(icon.specifier);
      lines.push(`declare module '${icon.specifier}' {`);
      if (icon.exportName && isValidIdentifier(icon.exportName)) {
        lines.push(`  export const ${icon.exportName}: unknown;`);
        lines.push(`  export default ${icon.exportName};`);
      } else {
        lines.push('  const PluginIconComponent: unknown;');
        lines.push('  export default PluginIconComponent;');
      }
      lines.push('}');
      lines.push('');
    }

    const databaseSpecifier = summary.databaseModuleSpecifier;
    if (databaseSpecifier) {
      const scopeTrimmed = databaseSpecifier.replace(/^@[^/]+\//, '');
      const hasSubpath = scopeTrimmed.includes('/');
      if (hasSubpath && !seen.has(databaseSpecifier)) {
        seen.add(databaseSpecifier);
        lines.push(`declare module '${databaseSpecifier}' {`);
        for (const target of summary.databasePrewarmTargets) {
          if (target.exportName && isValidIdentifier(target.exportName)) {
            lines.push(`  export const ${target.exportName}: unknown;`);
          }
        }
        lines.push('  const mod: Record<string, unknown>;');
        lines.push('  export default mod;');
        lines.push('}');
        lines.push('');
      }
    }
  }

  if (lines.length <= 2) {
    return '';
  }

  return `${lines.join('\n')}`.trimEnd() + `\n`;
}
