export type {
  ShapeProcessingState,
  ShapeProcessingStatus,
  ShapeTileLayerInfo,
  ShapeTileInfo,
  ShapeTileSummary,
  ShapeTileSummaryEntry,
  ShapeBuildProgressSummary,
  ShapeBuildSessionSummary,
  ShapeBuildTaskSummary,
} from './shapeTypes.js';
export type {
  ShapeDataSourceName,
  ShapeBuildStage,
  ShapeBuildTaskStatus,
  ShapeSourceTaskPayload,
  ShapeSourceTaskResult,
  ShapeGeometryTaskPayload,
  ShapeGeometryTaskResult,
  ShapeTileEmitTaskPayload,
  ShapeTileEmitTaskResult,
  ShapeBuildTaskPayload,
  ShapeBuildTaskResult,
  ShapeBuildTaskRecord,
  ShapeBuildTaskRecordInput,
  ShapeBuildTaskRecordUpdate,
  ShapeSourceCache,
  ShapeGeometryCache,
  ShapeTileEmitMetadata,
  ShapeFeatureMetadata,
  ShapeDataSourceMetadata,
  ShapeErrorLineString,
  ShapeErrorLineFeature,
  ShapeErrorLineFeatureCollection,
  ShapeGeometryErrorRecord,
} from './shapeBuildTypes.js';
export { DEFAULT_BUILD_CONFIG, DEFAULT_PROCESSING_CONFIG, DEFAULT_MAX_RATIO_VALUE } from './defaultConstants.js';
export type {
  ShapeBuildStopReason,
  ShapeSourceStageMaxima,
  ShapeBuildSessionRecord,
  ShapeFeatureRecord,
  ShapeVectorTileRecord,
  ShapeTileIdToBufferRelation,
  ShapeEphemeralSessionRecord,
} from './shapeDbTypes.js';
export type { ShapeQueryAPI } from './ShapeQueryAPI.js';
export type { ShapeMutationAPI } from './ShapeMutationAPI.js';
export {
  LEGACY_BUILD_STAGE_INACTIVE_MS_MISSING,
  RESET_LEGACY_BUILD_SESSION_AND_TASKS,
  ShapeBuildSessionContractError,
  isShapeBuildSessionContractError,
  isShapeBuildSessionRecoverableContractError,
  type ShapeBuildSessionProbeResult,
  type ShapeBuildSessionRecoverableContractError,
  type ShapeBuildSessionRecoveryDeletedRowCounts,
  type ShapeBuildSessionRecoveryRequest,
  type ShapeBuildSessionRecoveryResult,
} from './ShapeBuildSessionContractError.js';
