#!/usr/bin/env tsx
/**
 * Generate a combined plugin manifest file by reading all plugin packages
 * This script should be run at build time to collect plugin metadata
 */

import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

interface PluginManifest {
  nodeType: string;
  dependencies?: string[];
  extends?: string;
  version: string;
  description?: string;
}

interface CombinedManifest {
  generated: string;
  plugins: Record<string, PluginManifest>;
}

async function readPluginManifest(pluginDir: string): Promise<PluginManifest | null> {
  try {
    // Try to read plugin.manifest.json first
    const manifestPath = path.join(pluginDir, 'plugin.manifest.json');
    try {
      const manifestContent = await fs.readFile(manifestPath, 'utf-8');
      return JSON.parse(manifestContent);
    } catch {
      // Manifest doesn't exist, try to infer from package.json
    }

    // Read package.json as fallback
    const packageJsonPath = path.join(pluginDir, 'package.json');
    const packageContent = await fs.readFile(packageJsonPath, 'utf-8');
    const packageJson = JSON.parse(packageContent);
    
    // Extract plugin name from package name
    const match = packageJson.name?.match(/@hierarchidb\/node-type-(.+)-plugin/);
    if (!match) {
      return null;
    }
    
    const pluginName = match[1];
    
    // Analyze dependencies to find other plugins
    const dependencies: string[] = [];
    if (packageJson.dependencies) {
      for (const dep of Object.keys(packageJson.dependencies)) {
        const depMatch = dep.match(/@hierarchidb\/node-type-(.+)-plugin/);
        if (depMatch) {
          dependencies.push(depMatch[1]);
        }
      }
    }
    
    return {
      nodeType: pluginName,
      dependencies,
      version: packageJson.version || '1.0.0',
      description: packageJson.description
    };
  } catch (error) {
    console.error(`Failed to read plugin from ${pluginDir}:`, error);
    return null;
  }
}

async function generateManifests() {
  const rootDir = path.resolve(__dirname, '..');
  const nodeTypePluginDir = path.join(rootDir, 'packages', 'node-type-plugin');
  
  const combinedManifest: CombinedManifest = {
    generated: new Date().toISOString(),
    plugins: {}
  };

  try {
    // Read all directories in node-type-plugin
    const pluginDirs = await fs.readdir(nodeTypePluginDir);
    
    for (const dir of pluginDirs) {
      const pluginPath = path.join(nodeTypePluginDir, dir);
      const stat = await fs.stat(pluginPath);
      
      if (stat.isDirectory()) {
        console.log(`📦 Processing plugin: ${dir}`);
        const manifest = await readPluginManifest(pluginPath);
        
        if (manifest) {
          combinedManifest.plugins[manifest.nodeType] = manifest;
          console.log(`  ✅ Found plugin: ${manifest.nodeType}`);
          
          if (manifest.dependencies && manifest.dependencies.length > 0) {
            console.log(`     Dependencies: ${manifest.dependencies.join(', ')}`);
          }
          if (manifest.extends) {
            console.log(`     Extends: ${manifest.extends}`);
          }
        } else {
          console.log(`  ⏭️  Skipped (not a plugin or missing metadata)`);
        }
      }
    }
    
    // Write combined manifest
    const outputPath = path.join(rootDir, 'app', 'src', 'plugins', 'plugin-manifests.json');
    await fs.mkdir(path.dirname(outputPath), { recursive: true });
    await fs.writeFile(outputPath, JSON.stringify(combinedManifest, null, 2));
    
    console.log(`\n✨ Generated combined manifest with ${Object.keys(combinedManifest.plugins).length} plugins`);
    console.log(`📄 Output: ${outputPath}`);
    
    // Also generate TypeScript constants file
    const tsOutputPath = path.join(rootDir, 'app', 'src', 'plugins', 'plugin-manifests.ts');
    const tsContent = `// Auto-generated plugin manifests
// DO NOT EDIT - Generated by scripts/generate-plugin-manifests.ts

export const PLUGIN_MANIFESTS = ${JSON.stringify(combinedManifest.plugins, null, 2)} as const;

export const PLUGIN_MANIFEST_GENERATED = "${combinedManifest.generated}";

export type AvailablePlugin = keyof typeof PLUGIN_MANIFESTS;
`;
    
    await fs.writeFile(tsOutputPath, tsContent);
    console.log(`📄 TypeScript output: ${tsOutputPath}`);
    
  } catch (error) {
    console.error('❌ Failed to generate manifests:', error);
    process.exit(1);
  }
}

// Run the script
generateManifests().catch(console.error);