// scripts/split-exports.ts
// 例:
//   pnpm tsx scripts/split-exports.ts --root packages/common/api/src --dry-run=true --verbose --list
//   pnpm tsx scripts/split-exports.ts --root src --dry-run=false --no-deps=false

import {
  ClassDeclaration,
  EnumDeclaration,
  ExportDeclaration,
  ExportSpecifier,
  FunctionDeclaration,
  Identifier,
  ImportDeclaration,
  InterfaceDeclaration,
  Node,
  Project,
  SourceFile,
  SyntaxKind,
  TypeAliasDeclaration,
  // VariableDeclaration,
  VariableStatement,
} from 'ts-morph';
import * as globby from 'globby';
import type { Options as GlobbyOptions } from 'globby';
import minimist from 'minimist';
import * as path from 'node:path';
import * as fs from 'node:fs/promises';
import { pascalCase } from 'change-case';

// ===== CLI =====
type Args = {
  root?: string;
  tsconfig?: string; // 互換のため残す（本スクリプトでは未使用）
  dryRun?: boolean | string;
  exclude?: string | string[];
  includeIndex?: boolean | string;
  list?: boolean | string;
  verbose?: boolean | string;
  trace?: boolean | string;
  noDeps?: boolean | string;
};

// ===== Types =====
type DeclStatement =
  | VariableStatement
  | FunctionDeclaration
  | ClassDeclaration
  | InterfaceDeclaration
  | TypeAliasDeclaration
  | EnumDeclaration;

type PlanItem = {
  absPath: string;
  dir: string;
  ext: string;
  stem: string;
  backupPath: string;
  backupContent: string;
  shimPath: string;
  shimContent: string;
  symbolFiles: Array<{ path: string; content: string }>;
  publicNames: string[];
};

type DirIndex = Map<string, Set<string>>;

// ===== Utils =====
const t0 = Date.now();
const stamp = (): string => `${((Date.now() - t0) / 1000).toFixed(2)}s`;
const toBool = (v: unknown, def = false): boolean => String(v ?? String(def)) === 'true';
const rel = (p: string, base?: string): string =>
  (base ? path.relative(base, p) : p).split(path.sep).join('/');

/** デフォ除外 */
const DEFAULT_EXCLUDES: readonly string[] = [
  '**/*.d.ts',
  '**/*.backup',
  '**/__tests__/**',
  '**/__mocks__/**',
  '**/*.stories.{ts,tsx}',
  '**/*.{test,spec}.{ts,tsx}',

  // 設定ファイルいろいろ
  '**/*config.{ts,tsx}',
  '**/*.config.{ts,tsx}',
  '**/eslint.config.{ts,js,cjs,mjs}',
  '**/vite.config.{ts,tsx,js,cjs,mjs}',
  '**/vitest.config.{ts,tsx,js,cjs,mjs}',
  '**/playwright.config.{ts,tsx,js,cjs,mjs}',
  '**/tsup.config.{ts,tsx,js,cjs,mjs}',
  '**/rollup.config.{ts,tsx,js,cjs,mjs}',
  '**/tailwind.config.{ts,tsx,js,cjs,mjs}',

  // 成果物・キャッシュ
  '**/node_modules/**',
  '**/dist/**',
  '**/build/**',
  '**/.next/**',
  '**/.nuxt/**',
  '**/.output/**',
  '**/.vercel/**',
  '**/coverage/**',
  '**/.turbo/**',
  '**/.cache/**',
  '**/out/**',
  '**/cypress/**',
  '**/.storybook/**',
];

function normalizeExcludeArg(excludeArg?: string | string[]): string[] {
  if (!excludeArg) return [];
  const arr = Array.isArray(excludeArg) ? excludeArg : String(excludeArg).split(',');
  return arr.map((s) => s.trim()).filter(Boolean);
}

/** globby v14 を 2引数で呼ぶ（cwd=絶対パス） */
async function callGlobby(
  patterns: string[] | readonly string[],
  options: GlobbyOptions
): Promise<string[]> {
  const fn: any =
    (globby as any).globby ??
    (globby as any).default ??
    (typeof globby === 'function' ? globby : null);
  if (typeof fn !== 'function') throw new Error('globby function not found');
  return await fn(patterns, {
    ...options,
    absolute: true,
    onlyFiles: true,
    followSymbolicLinks: false,
    gitignore: true,
    unique: true,
  } as GlobbyOptions);
}

function hasNoSplitGuard(sf: SourceFile): boolean {
  const head = sf.getFullText().slice(0, 2048);
  return /^\s*\/\/\s*@nosplit\b/m.test(head);
}
function isGeneratedByOurTool(sf: SourceFile): boolean {
  const head = sf.getFullText().slice(0, 2048);
  return /@generated by split-with-deps/.test(head);
}

/** 修飾子が付いているか（Statement 全般に安全に使える） */
function hasModifier(node: Node, kind: SyntaxKind): boolean {
  const anyNode = node as any;
  if (typeof anyNode.getFirstModifierByKind === 'function') {
    return !!anyNode.getFirstModifierByKind(kind);
  }
  if (typeof anyNode.getModifiers === 'function') {
    const mods = anyNode.getModifiers() as any[];
    return Array.isArray(mods) && mods.some((m) => m.getKind?.() === kind);
  }
  return false;
}

/** import で導入されたローカル名集合（依存対象から除外） */
function getImportedLocalNames(sf: SourceFile): Set<string> {
  const s = new Set<string>();
  for (const imp of sf.getImportDeclarations()) {
    const d = imp.getDefaultImport();
    if (d) s.add(d.getText());
    const ns = imp.getNamespaceImport();
    if (ns) s.add(ns.getText());
    for (const ni of imp.getNamedImports()) {
      const local = ni.getAliasNode()?.getText() ?? ni.getNameNode().getText();
      s.add(local);
    }
  }
  return s;
}

/** ファイル内トップレベル「宣言名 → 代表ステートメント」対応表 */
function buildLocalDeclMap(sf: SourceFile): Map<string, DeclStatement> {
  const map = new Map<string, DeclStatement>();
  for (const st of sf.getStatements()) {
    if (Node.isFunctionDeclaration(st) || Node.isClassDeclaration(st)) {
      const name = st.getName();
      if (name) map.set(name, st as DeclStatement);
      continue;
    }
    if (
      Node.isInterfaceDeclaration(st) ||
      Node.isTypeAliasDeclaration(st) ||
      Node.isEnumDeclaration(st)
    ) {
      const name = st.getName();
      if (name) map.set(name, st as DeclStatement);
      continue;
    }
    if (Node.isVariableStatement(st)) {
      for (const d of st.getDeclarations()) {
        const name = d.getName();
        if (name) map.set(name, st);
      }
      continue;
    }
  }
  return map;
}

// 旧 isIdentifierReference を削除して、下記で置き換え
function isIdentifierReference(id: Identifier): boolean {
  const p = id.getParent();
  if (!p) return true;

  const anyP: any = p; // ランタイム能力検査で耐性アップ

  // 1) 「定義側の“名前”」は参照ではない
  //    getNameNode がある親（NamedNode系）で、その name がこの識別子なら定義側
  if (typeof anyP.getNameNode === 'function' && anyP.getNameNode() === id) {
    return false;
  }

  // 2) import句の識別子は参照ではない
  const pk = anyP.getKind?.();
  if (
    pk === SyntaxKind.ImportSpecifier ||
    pk === SyntaxKind.NamespaceImport ||
    pk === SyntaxKind.ImportClause
  ) {
    return false;
  }

  // 3) obj.prop / A.B の「右側の名前」は参照ではない（単なるプロパティ名/修飾名）
  if (pk === SyntaxKind.PropertyAccessExpression && typeof anyP.getNameNode === 'function') {
    if (anyP.getNameNode() === id) return false;
  }
  if (pk === SyntaxKind.QualifiedName && typeof anyP.getRight === 'function') {
    if (anyP.getRight() === id) return false;
  }

  // 4) オブジェクトリテラルのプロパティ名なども参照ではない（名前ノードを持つなら同上で弾けるが念のため）
  if ((Node as any).isPropertySignature?.(p) && (p as any).getNameNode?.() === id) {
    return false;
  }

  // ここまで除外に引っかからなければ参照とみなす
  return true;
}

/** 自前 export を AST で収集（TypeChecker不使用） */
function scanOwnExportsAST(sf: SourceFile): {
  named: Map<string, DeclStatement[]>;
  defaultDecl: DeclStatement | null; // export default class/func
  hasExportAssignment: boolean; // export default <expr>
  exportedPos: Set<number>; // export付き宣言の開始位置
} {
  const named = new Map<string, DeclStatement[]>();
  let defaultDecl: DeclStatement | null = null;
  let hasExportAssignment = false;
  const exportedPos = new Set<number>();

  for (const st of sf.getStatements()) {
    // export * from / export {..} from ... → re-export（自前ではない）
    if (Node.isExportDeclaration(st)) {
      const ed = st as ExportDeclaration;
      if (ed.getModuleSpecifierValue()) continue; // re-export はスキップ
      // export { Foo, Bar }; ← ローカルの再公開。宣言ノードが無いので後段で補足
      continue;
    }
    // export default <expr>;
    if (st.getKind() === SyntaxKind.ExportAssignment) {
      hasExportAssignment = true;
      continue;
    }

    const isExported = hasModifier(st, SyntaxKind.ExportKeyword);
    if (!isExported) continue;

    if (Node.isFunctionDeclaration(st) || Node.isClassDeclaration(st)) {
      const name = (st as FunctionDeclaration | ClassDeclaration).getName() ?? '';
      if (hasModifier(st, SyntaxKind.DefaultKeyword)) {
        defaultDecl = st as DeclStatement;
        exportedPos.add(st.getStart());
        if (name) {
          const arr = named.get(name) ?? [];
          arr.push(st as DeclStatement);
          named.set(name, arr);
        }
      } else if (name) {
        const arr = named.get(name) ?? [];
        arr.push(st as DeclStatement);
        named.set(name, arr);
        exportedPos.add(st.getStart());
      }
      continue;
    }

    if (
      Node.isInterfaceDeclaration(st) ||
      Node.isTypeAliasDeclaration(st) ||
      Node.isEnumDeclaration(st)
    ) {
      const name = (st as InterfaceDeclaration | TypeAliasDeclaration | EnumDeclaration).getName();
      if (name) {
        const arr = named.get(name) ?? [];
        arr.push(st as DeclStatement);
        named.set(name, arr);
        exportedPos.add(st.getStart());
      }
      continue;
    }

    if (Node.isVariableStatement(st)) {
      const vs = st as VariableStatement;
      for (const d of vs.getDeclarations()) {
        const name = d.getName();
        const arr = named.get(name) ?? [];
        arr.push(vs);
        named.set(name, arr);
      }
      exportedPos.add(st.getStart());
      continue;
    }
  }

  // export { Foo, Bar }（from なし）を補足（名前だけ）
  for (const st of sf.getStatements()) {
    if (!Node.isExportDeclaration(st)) continue;
    const ed = st as ExportDeclaration;
    if (ed.getModuleSpecifierValue()) continue; // re-export は除外
    for (const spec of ed.getNamedExports()) {
      const local: ExportSpecifier = spec;
      const name = local.getNameNode().getText();
      if (!named.has(name)) named.set(name, []);
    }
  }

  return { named, defaultDecl, hasExportAssignment, exportedPos };
}

function collectLocalDependencyDeclarationsAST(
  targets: Node[],
  _sf: SourceFile,
  exportedPos: Set<number>,
  localDeclByName: Map<string, DeclStatement>,
  importedNames: Set<string>
): DeclStatement[] {
  const queue: Node[] = targets.slice();
  const seenPos = new Set<number>();
  const out: DeclStatement[] = [];

  // ★ 追加: 追加できたかどうか返す
  function addStmt(stmt: DeclStatement): boolean {
    const pos = stmt.getStart();
    if (exportedPos.has(pos)) return false; // 既に export 済みは同梱不要
    if (seenPos.has(pos)) return false;
    seenPos.add(pos);
    out.push(stmt);
    return true;
  }

  while (queue.length) {
    const node = queue.pop() as Node;
    const ids: Identifier[] = node.getDescendantsOfKind(SyntaxKind.Identifier);
    for (const id of ids) {
      if (!isIdentifierReference(id)) continue;
      const name = id.getText();
      if (importedNames.has(name)) continue; // import 名は除外
      const decl = localDeclByName.get(name);
      if (!decl) continue;

      // ★ 追加: 新規に積めた時だけ再帰探索する
      if (addStmt(decl)) {
        queue.push(decl);
      }
    }
  }

  // 簡易順序調整（依存が先に来るように）
  out.sort((a, b) => a.getStart() - b.getStart());
  for (let pass = 0; pass < 2; pass++) {
    for (let i = 0; i < out.length; i++) {
      const A = out[i];
      const nameSet = new Set(
        A?.getDescendantsOfKind(SyntaxKind.Identifier).map((x) => x.getText())
      );
      for (let j = i + 1; j < out.length; j++) {
        const B = out[j];
        let bName = '';
        if (
          Node.isFunctionDeclaration(B) ||
          Node.isClassDeclaration(B) ||
          Node.isInterfaceDeclaration(B) ||
          Node.isTypeAliasDeclaration(B) ||
          Node.isEnumDeclaration(B)
        ) {
          bName = B.getName?.() ?? '';
        } else if (Node.isVariableStatement(B)) {
          bName = B.getDeclarations()
            .map((d) => d.getName())
            .join('|');
        }
        if (bName && nameSet.has(bName)) {
          const tmp = out[i];
          out[i] = out[j] as DeclStatement;
          out[j] = tmp as DeclStatement;
        }
      }
    }
  }
  return out;
}

/** includedNodes で参照された import のみ抽出（副作用 import は常に保持） */
function pickUsedImports(sf: SourceFile, includedNodes: Node[]): ImportDeclaration[] {
  const usedNames = new Set<string>();
  for (const n of includedNodes) {
    const ids = n.getDescendantsOfKind(SyntaxKind.Identifier);
    for (const id of ids) usedNames.add(id.getText());
  }

  const imports: ImportDeclaration[] = [];
  for (const imp of sf.getImportDeclarations()) {
    if (!imp.getImportClause()) {
      imports.push(imp); // 副作用 import
      continue;
    }
    const ns = imp.getNamespaceImport();
    const def = imp.getDefaultImport();
    const named = imp.getNamedImports();

    let keep = false;
    if (ns && usedNames.has(ns.getText())) keep = true;
    if (def && usedNames.has(def.getText())) keep = true;
    if (!keep) {
      for (const ni of named) {
        const local = ni.getNameNode().getText();
        const alias = ni.getAliasNode()?.getText();
        if (usedNames.has(alias ?? local)) {
          keep = true;
          break;
        }
      }
    }
    if (keep) imports.push(imp);
  }
  return imports;
}

function stripExportAndDefault(src: string): string {
  // 先頭の `export default` を最優先で除去
  let out = src.replace(/^\s*export\s+default\s+/m, '');
  // 次に先頭の `export` を一発だけ除去（async/abstract 等は残す）
  out = out.replace(/^\s*export\s+/m, '');
  return out;
}

// ヘルパ（ファイル先頭の utils 付近）
function uniquifyTargetName(
  dir: string,
  symName: string,
  ext: string,
  stem: string,
  used: Set<string>
): { filePath: string; fileBase: string } {
  let base = symName;
  let fp = path.join(dir, `${base}${ext}`);
  if (!used.has(fp)) return { filePath: fp, fileBase: base };

  // 衝突 → サフィックス付与（元ファイル名を参照）
  base = `${symName}__${stem.replace(/\W+/g, '_')}`;
  fp = path.join(dir, `${base}${ext}`);
  let i = 2;
  while (used.has(fp)) {
    base = `${symName}__${stem.replace(/\W+/g, '_')}_${i++}`;
    fp = path.join(dir, `${base}${ext}`);
  }
  return { filePath: fp, fileBase: base };
}

/** index.ts 用の集約に追加（値優先、型-only 同士なら型のまま維持） */
function addToDirIndex(di: DirIndex, dir: string, name: string, isTypeOnly: boolean): void {
  const m = di.get(dir) ?? new Map<string, boolean>();
  const prev = m.get(name);
  // 既存が false(値) なら維持、未登録 or true(型only) の時だけ上書きルール適用
  m.set(name, prev === undefined ? isTypeOnly : prev && isTypeOnly);
  di.set(dir, m);
}

// ===== Main =====
async function main(): Promise<void> {
  const argv = minimist(process.argv.slice(2)) as unknown as Args;
  const ROOT = argv.root ?? 'src';
  const ROOT_ABS = path.resolve(ROOT);
  const DRY = toBool(argv.dryRun, true);
  const VERBOSE = toBool(argv.verbose, false);
  const TRACE = toBool(argv.trace, false);
  const INCLUDE_INDEX = toBool(argv.includeIndex, false);
  const LIST = toBool(argv.list, false);
  const NO_DEPS = toBool(argv.noDeps, false);
  const EXTRA_EXCLUDES = normalizeExcludeArg(argv.exclude);

  console.log(`[${stamp()}] split-with-deps.fast start`);
  if (VERBOSE) {
    console.log(`  root=${ROOT} dryRun=${DRY} verbose=${VERBOSE} trace=${TRACE}`);
    console.log(`  excludes(default)=${DEFAULT_EXCLUDES.length} extra=${EXTRA_EXCLUDES.length}`);
  }

  // 1) scan
  if (VERBOSE) console.log(`[${stamp()}] scanning files...`);
  const ignore: string[] = [
    ...DEFAULT_EXCLUDES,
    ...(INCLUDE_INDEX ? [] : ['**/index.ts']),
    ...EXTRA_EXCLUDES,
  ];
  const files: string[] = await callGlobby(['**/*.ts', '**/*.tsx'], {
    cwd: ROOT_ABS,
    ignore,
  } as GlobbyOptions);
  if (VERBOSE) console.log(`[${stamp()}] scanning done: ${files.length} files`);
  if (LIST) {
    console.log('\nMatched files:');
    for (const f of files) console.log('  -', rel(f, ROOT_ABS));
    console.log('');
  }

  // 2) ts-morph project（軽量：tsconfigは読まない）
  if (VERBOSE) console.log(`[${stamp()}] create ts-morph Project (no tsconfig)`);
  const project = new Project({ skipAddingFilesFromTsConfig: true });

  // 3) analyze → plan
  if (VERBOSE) console.log(`[${stamp()}] analyzing...`);
  const plans: PlanItem[] = [];
  const dirIndex: DirIndex = new Map<string, Set<string>>();
  let processed = 0;

  for (const absPath of files) {
    const sf: SourceFile = project.addSourceFileAtPath(absPath);

    if (hasNoSplitGuard(sf)) {
      if (VERBOSE) console.log(`SKIP @nosplit: ${rel(absPath, ROOT_ABS)}`);
      continue;
    }
    if (isGeneratedByOurTool(sf)) {
      if (VERBOSE) console.log(`SKIP generated: ${rel(absPath, ROOT_ABS)}`);
      continue;
    }

    const { named, defaultDecl, hasExportAssignment, exportedPos } = scanOwnExportsAST(sf);

    // export default <expr> は安全のためスキップ（必要なら後で個別対応）
    if (hasExportAssignment) {
      if (VERBOSE) console.log(`SKIP export-assignment: ${rel(absPath, ROOT_ABS)}`);
      continue;
    }

    if (named.size === 0 && !defaultDecl) {
      processed++;
      continue;
    }

    const dir = path.dirname(absPath);
    const ext = path.extname(absPath);
    const stem = path.basename(absPath).replace(/\.(tsx|ts)$/i, '');
    const originalContent = await fs.readFile(absPath, 'utf8');

    const shimLines: string[] = [];
    const symbolFiles: Array<{ path: string; content: string }> = [];
    const publicNames: string[] = [];

    const importedNames = getImportedLocalNames(sf);
    const localDeclByName = buildLocalDeclMap(sf);

    // default export
    let defaultName: string | null = null;
    if (defaultDecl) {
      defaultName =
        Node.isFunctionDeclaration(defaultDecl) || Node.isClassDeclaration(defaultDecl)
          ? (defaultDecl.getName() ?? pascalCase(stem))
          : pascalCase(stem);

      const deps = NO_DEPS
        ? []
        : collectLocalDependencyDeclarationsAST(
            [defaultDecl],
            sf,
            exportedPos,
            localDeclByName,
            importedNames
          );
      const usedImports = pickUsedImports(sf, [...deps, defaultDecl]);

      const header = `/* @generated by split-with-deps: ${rel(absPath, ROOT_ABS)} -> ${defaultName}${ext} */\n`;
      const importsText = usedImports.length
        ? usedImports.map((i) => i.getText()).join('\n') + '\n'
        : '';
      const depsText = deps.length ? deps.map((s) => s.getText()).join('\n\n') + '\n\n' : '';

      let bodyText = stripExportAndDefault(defaultDecl.getText());

      // 無名 default のときは命名
      if (Node.isFunctionDeclaration(defaultDecl) && !defaultDecl.getName()) {
        bodyText = bodyText.replace(/^(\s*)function\b/, `$1function ${defaultName}`);
      }
      if (Node.isClassDeclaration(defaultDecl) && !defaultDecl.getName()) {
        bodyText = bodyText.replace(/^(\s*)class\b/, `$1class ${defaultName}`);
      }

      // declare のときはそのまま、それ以外は export を先頭に付与
      const exportedBody = bodyText.trimStart().startsWith('declare ')
        ? bodyText
        : bodyText.replace(
            /^(?=(\s*)(class|function|interface|type|enum|const|let|var)\b)/m,
            'export '
          );

      const content = [header, importsText, depsText, exportedBody, '\n'].join('');
      symbolFiles.push({ path: path.join(dir, `${defaultName}${ext}`), content });

      shimLines.push(`export { ${defaultName} as default } from './${defaultName}';`);
      publicNames.push(defaultName);
    }

    // named exports
    for (const [symName, decls] of named) {
      if (defaultName && symName === defaultName) continue;

      // export { Foo } ; のように宣言ノードが無いときは shim だけ
      if (!decls || decls.length === 0) {
        shimLines.push(`export { ${symName} } from './${stem}';`);
        publicNames.push(symName);
        continue;
      }

      const decl =
        decls.find((d) => (Node.isFunctionDeclaration(d) ? !!d.getBody() : true)) ?? decls[0];

      const deps = NO_DEPS
        ? []
        : collectLocalDependencyDeclarationsAST(
            [decl as Node],
            sf,
            exportedPos,
            localDeclByName,
            importedNames
          );
      const usedImports = pickUsedImports(sf, [...deps, decl as Node]);

      const header = `/* @generated by split-with-deps: ${rel(absPath, ROOT_ABS)} -> ${symName}${ext} */\n`;
      const importsText = usedImports.length
        ? usedImports.map((i) => i.getText()).join('\n') + '\n'
        : '';
      const depsText = deps.length ? deps.map((s) => s.getText()).join('\n\n') + '\n\n' : '';

      let bodyText = stripExportAndDefault((decl as Node).getText());

      const exportedBody = bodyText.trimStart().startsWith('declare ')
        ? bodyText
        : bodyText.replace(
            /^(?=(\s*)(class|function|interface|type|enum|const|let|var)\b)/m,
            'export '
          );

      const content = [header, importsText, depsText, exportedBody, '\n'].join('');
      symbolFiles.push({ path: path.join(dir, `${symName}${ext}`), content });

      shimLines.push(`export { ${symName} } from './${symName}';`);
      publicNames.push(symName);
    }

    const plan: PlanItem = {
      absPath,
      dir,
      ext,
      stem,
      backupPath: path.join(dir, `${stem}${ext}.backup`),
      backupContent: originalContent,
      shimPath: absPath,
      shimContent: shimLines.join('\n') + '\n',
      symbolFiles,
      publicNames,
    };
    plans.push(plan);

    const setForDir = dirIndex.get(dir) ?? new Set<string>();
    publicNames.forEach((n) => setForDir.add(n));
    dirIndex.set(dir, setForDir);

    processed++;
    if (VERBOSE && processed % 10 === 0) {
      console.log(`[${stamp()}] analyzed ${processed}/${files.length}`);
    }
  }

  if (VERBOSE) console.log(`[${stamp()}] analyzing done: ${plans.length} plans`);

  // 4) write（dry-run ならログのみ）
  if (VERBOSE) console.log(`[${stamp()}] writing...`);
  const tWrite0 = Date.now();

  for (const p of plans) {
    if (!DRY) {
      // バックアップ（既存があれば連番）
      let backupPath = p.backupPath;
      let i = 2;
      // 競合しないファイル名が見つかるまで wx で作成
      while (true) {
        try {
          await fs.writeFile(backupPath, p.backupContent, { flag: 'wx' });
          break;
        } catch (e: any) {
          if (e && e.code === 'EEXIST') {
            backupPath = path.join(p.dir, `${p.stem}${p.ext}.backup.${i++}`);
            continue;
          }
          throw e;
        }
      }
    }
    console.log(`BACKUP:  ${rel(p.absPath, ROOT_ABS)} -> ${rel(p.backupPath, ROOT_ABS)}`);

    for (const f of p.symbolFiles) {
      if (!DRY) await fs.writeFile(f.path, f.content, 'utf8');
      console.log(`WRITE:   ${rel(f.path, ROOT_ABS)}`);
    }

    if (!DRY) await fs.writeFile(p.shimPath, p.shimContent, 'utf8');
    console.log(`SHIM:    ${rel(p.shimPath, ROOT_ABS)}`);
  }

  // index.ts（明示列挙）
  for (const [dir, names] of dirIndex.entries()) {
    const indexPath = path.join(dir, 'index.ts');
    const list = Array.from(names).sort();
    const lines = list.map((n) => `export { ${n} } from './${n}';`);
    const content = lines.join('\n') + '\n';
    if (!DRY) await fs.writeFile(indexPath, content, 'utf8');
    console.log(`INDEX:   ${rel(indexPath, ROOT_ABS)} (${list.length} symbols)`);
  }

  if (TRACE) {
    const dur = ((Date.now() - tWrite0) / 1000).toFixed(2);
    console.log(`[${stamp()}] write done in ${dur}s`);
  }

  console.log(DRY ? '\n[Dry Run] 変更は未反映です。--dry-run=false で実行します。' : '\nDone.');
}

main().catch((e: unknown) => {
  console.error(e instanceof Error ? `${e.name}: ${e.message}\n${e.stack ?? ''}` : String(e));
  process.exit(1);
});
