// scripts/split-exports2.ts
// 例:
//   pnpm tsx scripts/split-exports2.ts --root packages/common/core/src --dry-run=true --verbose --list
//   pnpm tsx scripts/split-exports2.ts --root src --dry-run=false --no-deps=false

import {
  ClassDeclaration,
  EnumDeclaration,
  ExportDeclaration,
  ExportSpecifier,
  FunctionDeclaration,
  Identifier,
  ImportDeclaration,
  InterfaceDeclaration,
  Node,
  Project,
  SourceFile,
  SyntaxKind,
  TypeAliasDeclaration,
  //VariableDeclaration,
  VariableStatement,
} from 'ts-morph';
import * as globby from 'globby';
import type { Options as GlobbyOptions } from 'globby';
import minimist from 'minimist';
import * as path from 'node:path';
import * as fs from 'node:fs/promises';
import { pascalCase } from 'change-case';

// ===== CLI =====
type Args = {
  root?: string;
  tsconfig?: string; // 互換のため残す（未使用）
  dryRun?: boolean | string;
  exclude?: string | string[];
  includeIndex?: boolean | string;
  list?: boolean | string;
  verbose?: boolean | string;
  trace?: boolean | string;
  noDeps?: boolean | string;
};

// ===== Types =====
type DeclStatement =
  | VariableStatement
  | FunctionDeclaration
  | ClassDeclaration
  | InterfaceDeclaration
  | TypeAliasDeclaration
  | EnumDeclaration;

type PlanItem = {
  absPath: string;
  dir: string;
  ext: string;
  stem: string;
  backupPath: string;
  backupContent: string;
  shimPath: string;
  shimContent: string;
  symbolFiles: Array<{ path: string; content: string }>;
  publicNames: string[];
};

// name -> isTypeOnly（true=型のみ, false=値/型両用）
type DirIndex = Map<string, Map<string, boolean>>;

// ===== Utils =====
const t0 = Date.now();
const stamp = (): string => `${((Date.now() - t0) / 1000).toFixed(2)}s`;
const toBool = (v: unknown, def = false): boolean => String(v ?? String(def)) === 'true';
const rel = (p: string | undefined, base?: string): string | undefined =>
  p ? (base ? path.relative(base, p) : p).split(path.sep).join('/') : undefined;

/** デフォ除外 */
const DEFAULT_EXCLUDES: readonly string[] = [
  '**/*.d.ts',
  '**/*.backup',
  '**/__tests__/**',
  '**/__mocks__/**',
  '**/*.stories.{ts,tsx}',
  '**/*.{test,spec}.{ts,tsx}',

  // 設定ファイル
  '**/*config.{ts,tsx}',
  '**/*.config.{ts,tsx}',
  '**/eslint.config.{ts,js,cjs,mjs}',
  '**/vite.config.{ts,tsx,js,cjs,mjs}',
  '**/vitest.config.{ts,tsx,js,cjs,mjs}',
  '**/playwright.config.{ts,tsx,js,cjs,mjs}',
  '**/tsup.config.{ts,tsx,js,cjs,mjs}',
  '**/rollup.config.{ts,tsx,js,cjs,mjs}',
  '**/tailwind.config.{ts,tsx,js,cjs,mjs}',

  // 成果物・キャッシュ
  '**/node_modules/**',
  '**/dist/**',
  '**/build/**',
  '**/.next/**',
  '**/.nuxt/**',
  '**/.output/**',
  '**/.vercel/**',
  '**/coverage/**',
  '**/.turbo/**',
  '**/.cache/**',
  '**/out/**',
  '**/cypress/**',
  '**/.storybook/**',
];

function normalizeExcludeArg(excludeArg?: string | string[]): string[] {
  if (!excludeArg) return [];
  const arr = Array.isArray(excludeArg) ? excludeArg : String(excludeArg).split(',');
  return arr.map((s) => s.trim()).filter(Boolean);
}

/** globby v14 を 2引数で安全に呼ぶ（cwdは絶対パス） */
async function callGlobby(
  patterns: string[] | readonly string[],
  options: GlobbyOptions
): Promise<string[]> {
  const fn: any =
    (globby as any).globby ??
    (globby as any).default ??
    (typeof globby === 'function' ? globby : null);
  if (typeof fn !== 'function') throw new Error('globby function not found');
  return await fn(patterns, {
    ...options,
    absolute: true,
    onlyFiles: true,
    followSymbolicLinks: false,
    gitignore: true,
    unique: true,
  } as GlobbyOptions);
}

function hasNoSplitGuard(sf: SourceFile): boolean {
  const head = sf.getFullText().slice(0, 2048);
  return /^\s*\/\/\s*@nosplit\b/m.test(head);
}
function isGeneratedByOurTool(sf: SourceFile): boolean {
  const head = sf.getFullText().slice(0, 2048);
  return /@generated by split-with-deps/.test(head);
}

/** 修飾子が付いているか（Statement 全般に安全） */
function hasModifier(node: Node, kind: SyntaxKind): boolean {
  const anyNode = node as any;
  if (typeof anyNode.getFirstModifierByKind === 'function') {
    return !!anyNode.getFirstModifierByKind(kind);
  }
  if (typeof anyNode.getModifiers === 'function') {
    const mods = anyNode.getModifiers() as any[];
    return Array.isArray(mods) && mods.some((m) => m.getKind?.() === kind);
  }
  return false;
}

/** import で導入されたローカル名集合（依存対象から除外） */
function getImportedLocalNames(sf: SourceFile): Set<string> {
  const s = new Set<string>();
  for (const imp of sf.getImportDeclarations()) {
    imp.getDefaultImport()?.getText() && s.add(imp.getDefaultImport()!.getText());
    imp.getNamespaceImport()?.getText() && s.add(imp.getNamespaceImport()!.getText());
    for (const ni of imp.getNamedImports()) {
      const local = ni.getAliasNode()?.getText() ?? ni.getNameNode().getText();
      s.add(local);
    }
  }
  return s;
}

/** ファイル内トップレベル「宣言名 → 代表ステートメント」対応表 */
function buildLocalDeclMap(sf: SourceFile): Map<string, DeclStatement> {
  const map = new Map<string, DeclStatement>();
  for (const st of sf.getStatements()) {
    if (Node.isFunctionDeclaration(st) || Node.isClassDeclaration(st)) {
      const name = st.getName();
      if (name) map.set(name, st as DeclStatement);
      continue;
    }
    if (
      Node.isInterfaceDeclaration(st) ||
      Node.isTypeAliasDeclaration(st) ||
      Node.isEnumDeclaration(st)
    ) {
      const name = st.getName();
      if (name) map.set(name, st as DeclStatement);
      continue;
    }
    if (Node.isVariableStatement(st)) {
      for (const d of st.getDeclarations()) {
        const name = d.getName();
        if (name) map.set(name, st);
      }
      continue;
    }
  }
  return map;
}

/** 参照として数える Identifier 判定（定義名/プロパティ名/型名などは除外） */
function isIdentifierReference(id: Identifier): boolean {
  const p = id.getParent();
  if (!p) return true;

  const anyP: any = p;

  // 親が getNameNode を持ち、その name が自分なら「定義側」
  if (typeof anyP.getNameNode === 'function' && anyP.getNameNode() === id) {
    return false;
  }

  // import句の識別子は参照ではない
  const pk = anyP.getKind?.();
  if (
    pk === SyntaxKind.ImportSpecifier ||
    pk === SyntaxKind.NamespaceImport ||
    pk === SyntaxKind.ImportClause
  ) {
    return false;
  }

  // obj.prop / A.B の右側名は参照ではない（単なる名称）
  if (pk === SyntaxKind.PropertyAccessExpression && typeof anyP.getNameNode === 'function') {
    if (anyP.getNameNode() === id) return false;
  }
  if (pk === SyntaxKind.QualifiedName && typeof anyP.getRight === 'function') {
    if (anyP.getRight() === id) return false;
  }

  // PropertySignature の名前など（念のため）
  if ((Node as any).isPropertySignature?.(p) && (p as any).getNameNode?.() === id) {
    return false;
  }

  return true;
}

/** 自前 export を AST で収集（TypeChecker不使用） */
function scanOwnExportsAST(sf: SourceFile): {
  named: Map<string, DeclStatement[]>;
  defaultDecl: DeclStatement | null; // export default class/func
  hasExportAssignment: boolean; // export default <expr>
  exportedPos: Set<number>; // export付き宣言の開始位置
} {
  const named = new Map<string, DeclStatement[]>();
  let defaultDecl: DeclStatement | null = null;
  let hasExportAssignment = false;
  const exportedPos = new Set<number>();

  for (const st of sf.getStatements()) {
    // export * from / export {..} from ... → re-export（自前ではない）
    if (Node.isExportDeclaration(st)) {
      const ed = st as ExportDeclaration;
      if (ed.getModuleSpecifierValue()) continue; // re-export はスキップ
      continue; // export { Foo, Bar }; は後段で補足
    }
    // export default <expr>;
    if (st.getKind() === SyntaxKind.ExportAssignment) {
      hasExportAssignment = true;
      continue;
    }

    const isExported = hasModifier(st, SyntaxKind.ExportKeyword);
    if (!isExported) continue;

    if (Node.isFunctionDeclaration(st) || Node.isClassDeclaration(st)) {
      const name = (st as FunctionDeclaration | ClassDeclaration).getName() ?? '';
      if (hasModifier(st, SyntaxKind.DefaultKeyword)) {
        defaultDecl = st as DeclStatement;
        exportedPos.add(st.getStart());
        if (name) {
          const arr = named.get(name) ?? [];
          arr.push(st as DeclStatement);
          named.set(name, arr);
        }
      } else if (name) {
        const arr = named.get(name) ?? [];
        arr.push(st as DeclStatement);
        named.set(name, arr);
        exportedPos.add(st.getStart());
      }
      continue;
    }

    if (
      Node.isInterfaceDeclaration(st) ||
      Node.isTypeAliasDeclaration(st) ||
      Node.isEnumDeclaration(st)
    ) {
      const name = (st as InterfaceDeclaration | TypeAliasDeclaration | EnumDeclaration).getName();
      if (name) {
        const arr = named.get(name) ?? [];
        arr.push(st as DeclStatement);
        named.set(name, arr);
        exportedPos.add(st.getStart());
      }
      continue;
    }

    if (Node.isVariableStatement(st)) {
      const vs = st as VariableStatement;
      for (const d of vs.getDeclarations()) {
        const name = d.getName();
        const arr = named.get(name) ?? [];
        arr.push(vs);
        named.set(name, arr);
      }
      exportedPos.add(st.getStart());
      continue;
    }
  }

  // export { Foo, Bar }（from なし）を補足（名前だけ）
  for (const st of sf.getStatements()) {
    if (!Node.isExportDeclaration(st)) continue;
    const ed = st as ExportDeclaration;
    if (ed.getModuleSpecifierValue()) continue; // re-export は除外
    for (const spec of ed.getNamedExports()) {
      const local: ExportSpecifier = spec;
      const name = local.getNameNode().getText();
      if (!named.has(name)) named.set(name, []);
    }
  }

  return { named, defaultDecl, hasExportAssignment, exportedPos };
}

/** 依存（同一ファイルの非export）を再帰収集（純AST・シンボル解決なし） */
function collectLocalDependencyDeclarationsAST(
  targets: Node[],
  _sf: SourceFile,
  exportedPos: Set<number>,
  localDeclByName: Map<string, DeclStatement>,
  importedNames: Set<string>
): DeclStatement[] {
  const queue: Node[] = targets.slice();
  const seenPos = new Set<number>();
  const out: DeclStatement[] = [];

  // 新規に追加できたら true を返す（無限ループ防止）
  function addStmt(stmt: DeclStatement): boolean {
    const pos = stmt.getStart();
    if (exportedPos.has(pos)) return false; // 既に export 済みは同梱不要
    if (seenPos.has(pos)) return false;
    seenPos.add(pos);
    out.push(stmt);
    return true;
  }

  while (queue.length) {
    const node = queue.pop() as Node;
    const ids: Identifier[] = node.getDescendantsOfKind(SyntaxKind.Identifier);
    for (const id of ids) {
      if (!isIdentifierReference(id)) continue;
      const name = id.getText();
      if (importedNames.has(name)) continue; // import 名は除外
      const decl = localDeclByName.get(name);
      if (!decl) continue;
      if (addStmt(decl)) {
        queue.push(decl);
      }
    }
  }

  // 簡易順序調整（依存が先に来るように）
  out.sort((a, b) => a.getStart() - b.getStart());
  for (let pass = 0; pass < 2; pass++) {
    for (let i = 0; i < out.length; i++) {
      const A = out[i];
      const nameSet = new Set(
        A?.getDescendantsOfKind(SyntaxKind.Identifier).map((x) => x.getText())
      );
      for (let j = i + 1; j < out.length; j++) {
        const B = out[j];
        let bName = '';
        if (
          Node.isFunctionDeclaration(B) ||
          Node.isClassDeclaration(B) ||
          Node.isInterfaceDeclaration(B) ||
          Node.isTypeAliasDeclaration(B) ||
          Node.isEnumDeclaration(B)
        ) {
          bName = B.getName?.() ?? '';
        } else if (Node.isVariableStatement(B)) {
          bName = B.getDeclarations()
            .map((d) => d.getName())
            .join('|');
        }
        if (bName && nameSet.has(bName)) {
          const tmp = out[i];
          out[i] = out[j] as DeclStatement;
          out[j] = tmp as DeclStatement;
        }
      }
    }
  }
  return out;
}

/** includedNodes で参照された import のみ抽出（副作用 import は常に保持） */
function pickUsedImports(sf: SourceFile, includedNodes: Node[]): ImportDeclaration[] {
  const usedNames = new Set<string>();
  for (const n of includedNodes) {
    const ids = n.getDescendantsOfKind(SyntaxKind.Identifier);
    for (const id of ids) usedNames.add(id.getText());
  }

  const imports: ImportDeclaration[] = [];
  for (const imp of sf.getImportDeclarations()) {
    if (!imp.getImportClause()) {
      imports.push(imp); // 副作用 import
      continue;
    }
    const ns = imp.getNamespaceImport();
    const def = imp.getDefaultImport();
    const named = imp.getNamedImports();

    let keep = false;
    if (ns && usedNames.has(ns.getText())) keep = true;
    if (def && usedNames.has(def.getText())) keep = true;
    if (!keep) {
      for (const ni of named) {
        const local = ni.getNameNode().getText();
        const alias = ni.getAliasNode()?.getText();
        if (usedNames.has(alias ?? local)) {
          keep = true;
          break;
        }
      }
    }
    if (keep) imports.push(imp);
  }
  return imports;
}

/** export / export default の除去（テキスト置換・安全） */
function stripExportAndDefault(src: string): string {
  let out = src.replace(/^\s*export\s+default\s+/m, '');
  out = out.replace(/^\s*export\s+/m, '');
  return out;
}

/** 生成ファイル名の衝突回避: 同dirに同名が予定済みなら __<stem> を付ける */
function uniquifyTargetName(
  dir: string,
  symName: string,
  ext: string,
  stem: string,
  used: Set<string>
): { filePath: string; fileBase: string } {
  let base = symName;
  let fp = path.join(dir, `${base}${ext}`);
  if (!used.has(fp)) return { filePath: fp, fileBase: base };

  const stemTag = stem.replace(/\W+/g, '_') || 'x';
  base = `${symName}__${stemTag}`;
  fp = path.join(dir, `${base}${ext}`);

  let i = 2;
  while (used.has(fp)) {
    base = `${symName}__${stemTag}_${i++}`;
    fp = path.join(dir, `${base}${ext}`);
  }
  return { filePath: fp, fileBase: base };
}

/** index.ts 用の集約に追加（値優先・型only同士は型のまま） */
function addToDirIndex(di: DirIndex, dir: string, name: string, isTypeOnly: boolean): void {
  const m: Map<string, boolean> = di.get(dir) ?? new Map<string, boolean>();
  const prev = m.get(name);
  m.set(name, prev === undefined ? isTypeOnly : prev && isTypeOnly);
  di.set(dir, m);
}

// ===== Main =====
async function main(): Promise<void> {
  const argv = minimist(process.argv.slice(2), {
    alias: {
      root: ['r'],
      tsconfig: [],
      'dry-run': ['dryRun'],
      'include-index': ['includeIndex'],
      'no-deps': ['noDeps'],
      list: ['ls'],
      verbose: ['v'],
      trace: ['t'],
      exclude: [],
    },
    boolean: ['dry-run', 'include-index', 'no-deps', 'list', 'verbose', 'trace'],
    string: ['root', 'tsconfig', 'exclude'],
    default: {
      'dry-run': true,
      verbose: false,
      trace: false,
      'include-index': false,
      list: false,
      'no-deps': false,
    },
  }) as any;
  const ROOT = argv.root ?? 'src';
  const ROOT_ABS: string = path.resolve(ROOT);
  const DRY: boolean = argv['dry-run'] as boolean; // ← ここが本命
  const VERBOSE = toBool(argv.verbose, false);
  const TRACE = toBool(argv.trace, false);
  const INCLUDE_INDEX = toBool(argv.includeIndex, false);
  const LIST = toBool(argv.list, false);
  const NO_DEPS = toBool(argv.noDeps, false);
  const EXTRA_EXCLUDES = normalizeExcludeArg(argv.exclude);

  console.log(`[${stamp()}] split-with-deps.fast start`);
  if (VERBOSE) {
    console.log(`  root=${ROOT} dryRun=${DRY} verbose=${VERBOSE} trace=${TRACE}`);
    console.log(`  excludes(default)=${DEFAULT_EXCLUDES.length} extra=${EXTRA_EXCLUDES.length}`);
  }

  // 1) scan
  if (VERBOSE) console.log(`[${stamp()}] scanning files...`);
  const ignore: string[] = [
    ...DEFAULT_EXCLUDES,
    ...(INCLUDE_INDEX ? [] : ['**/index.ts']),
    ...EXTRA_EXCLUDES,
  ];
  const files: string[] = await callGlobby(['**/*.ts', '**/*.tsx'], {
    cwd: ROOT_ABS,
    ignore,
  } as GlobbyOptions);
  if (VERBOSE) console.log(`[${stamp()}] scanning done: ${files.length} files`);
  if (LIST) {
    console.log('\nMatched files:');
    for (const f of files) console.log('  -', rel(f, ROOT_ABS));
    console.log('');
  }

  // 2) ts-morph project（軽量：tsconfigは読まない）
  if (VERBOSE) console.log(`[${stamp()}] create ts-morph Project (no tsconfig)`);
  const project = new Project({ skipAddingFilesFromTsConfig: true });

  // 3) analyze → plan
  if (VERBOSE) console.log(`[${stamp()}] analyzing...`);

  // ★ 全体で共有：生成予定パスの一意化セット
  const plannedPaths = new Set<string>();

  const plans: PlanItem[] = [];
  const dirIndex: DirIndex = new Map<string, Map<string, boolean>>();
  let processed = 0;

  for (let idx = 0; idx < files.length; idx++) {
    const absPath = files[idx];
    if (VERBOSE)
      console.log(`[${stamp()}] analyze ${idx + 1}/${files.length}: ${rel(absPath, ROOT_ABS)}`);

    if (!absPath) {
      if (VERBOSE) console.log(`SKIP empty: ${rel(absPath, ROOT_ABS)}`);
      continue;
    }

    const sf: SourceFile = project.addSourceFileAtPath(absPath);

    if (hasNoSplitGuard(sf)) {
      if (VERBOSE) console.log(`SKIP @nosplit: ${rel(absPath, ROOT_ABS)}`);
      continue;
    }
    if (isGeneratedByOurTool(sf)) {
      if (VERBOSE) console.log(`SKIP generated: ${rel(absPath, ROOT_ABS)}`);
      continue;
    }

    const { named, defaultDecl, hasExportAssignment, exportedPos } = scanOwnExportsAST(sf);

    // export default <expr> は安全のためスキップ（必要なら個別対応）
    if (hasExportAssignment) {
      if (VERBOSE) console.log(`SKIP export-assignment: ${rel(absPath, ROOT_ABS)}`);
      continue;
    }

    if (named.size === 0 && !defaultDecl) {
      processed++;
      continue;
    }

    const dir = path.dirname(absPath);
    const ext = path.extname(absPath);
    const stem = path.basename(absPath).replace(/\.(tsx|ts)$/i, '');
    const originalContent = await fs.readFile(absPath, 'utf8');

    const shimLines: string[] = [];
    const symbolFiles: Array<{ path: string; content: string }> = [];
    const publicNames: string[] = [];

    const importedNames = getImportedLocalNames(sf);
    const localDeclByName = buildLocalDeclMap(sf);

    // default export
    let defaultName: string | null = null;
    if (defaultDecl) {
      defaultName =
        Node.isFunctionDeclaration(defaultDecl) || Node.isClassDeclaration(defaultDecl)
          ? (defaultDecl.getName() ?? pascalCase(stem))
          : pascalCase(stem);

      const deps = NO_DEPS
        ? []
        : collectLocalDependencyDeclarationsAST(
            [defaultDecl],
            sf,
            exportedPos,
            localDeclByName,
            importedNames
          );
      const usedImports = pickUsedImports(sf, [...deps, defaultDecl]);

      const header = `/* @generated by split-with-deps: ${rel(absPath, ROOT_ABS)} -> ${defaultName}${ext} */\n`;
      const importsText = usedImports.length
        ? usedImports.map((i) => i.getText()).join('\n') + '\n'
        : '';
      const depsText = deps.length ? deps.map((s) => s.getText()).join('\n\n') + '\n\n' : '';

      let bodyText = stripExportAndDefault(defaultDecl.getText());
      if (Node.isFunctionDeclaration(defaultDecl) && !defaultDecl.getName()) {
        bodyText = bodyText.replace(/^(\s*)function\b/, `$1function ${defaultName}`);
      }
      if (Node.isClassDeclaration(defaultDecl) && !defaultDecl.getName()) {
        bodyText = bodyText.replace(/^(\s*)class\b/, `$1class ${defaultName}`);
      }
      const exportedBody = bodyText.trimStart().startsWith('declare ')
        ? bodyText
        : bodyText.replace(
            /^(?=(\s*)(class|function|interface|type|enum|const|let|var)\b)/m,
            'export '
          );

      const content = [header, importsText, depsText, exportedBody, '\n'].join('');

      const { filePath: defPath, fileBase: defBase } = uniquifyTargetName(
        dir,
        defaultName,
        ext,
        stem,
        plannedPaths
      );
      plannedPaths.add(defPath);

      symbolFiles.push({ path: defPath, content });

      shimLines.push(`export { ${defBase} as default } from './${defBase}';`);
      publicNames.push(defBase);

      // default は値扱い
      addToDirIndex(dirIndex, dir, defBase, /*isTypeOnly*/ false);
    }

    // named exports
    for (const [symName, decls] of named) {
      if (defaultName && symName === defaultName) continue;

      // export { Foo } ; のみ（宣言ノード不明）の場合は元ファイルを再公開
      if (!decls || decls.length === 0) {
        shimLines.push(`export { ${symName} } from './${stem}';`);
        publicNames.push(symName);
        addToDirIndex(dirIndex, dir, symName, /*isTypeOnly*/ false);
        continue;
      }

      const decl =
        decls.find((d) => (Node.isFunctionDeclaration(d) ? !!d.getBody() : true)) ?? decls[0];

      const deps = NO_DEPS
        ? []
        : collectLocalDependencyDeclarationsAST(
            [decl as Node],
            sf,
            exportedPos,
            localDeclByName,
            importedNames
          );
      const usedImports = pickUsedImports(sf, [...deps, decl as Node]);

      const header = `/* @generated by split-with-deps: ${rel(absPath, ROOT_ABS)} -> ${symName}${ext} */\n`;
      const importsText = usedImports.length
        ? usedImports.map((i) => i.getText()).join('\n') + '\n'
        : '';
      const depsText = deps.length ? deps.map((s) => s.getText()).join('\n\n') + '\n\n' : '';

      let bodyText = stripExportAndDefault((decl as Node).getText());
      const exportedBody = bodyText.trimStart().startsWith('declare ')
        ? bodyText
        : bodyText.replace(
            /^(?=(\s*)(class|function|interface|type|enum|const|let|var)\b)/m,
            'export '
          );

      const content = [header, importsText, depsText, exportedBody, '\n'].join('');

      const { filePath, fileBase } = uniquifyTargetName(dir, symName, ext, stem, plannedPaths);
      plannedPaths.add(filePath);

      symbolFiles.push({ path: filePath, content });

      const isTypeOnly = Node.isInterfaceDeclaration(decl) || Node.isTypeAliasDeclaration(decl);

      if (isTypeOnly) {
        shimLines.push(`export type { ${fileBase} } from './${fileBase}';`);
      } else {
        shimLines.push(`export { ${fileBase} } from './${fileBase}';`);
      }
      publicNames.push(fileBase);

      addToDirIndex(dirIndex, dir, fileBase, isTypeOnly);
    }

    const plan: PlanItem = {
      absPath,
      dir,
      ext,
      stem,
      backupPath: path.join(dir, `${stem}${ext}.backup`),
      backupContent: originalContent,
      shimPath: absPath,
      shimContent: shimLines.join('\n') + '\n',
      symbolFiles,
      publicNames,
    };
    plans.push(plan);

    processed++;
    if (VERBOSE && processed % 10 === 0) {
      console.log(`[${stamp()}] analyzed ${processed}/${files.length}`);
    }
  }

  if (VERBOSE) console.log(`[${stamp()}] analyzing done: ${plans.length} plans`);

  // 4) write（dry-run ならログのみ）
  if (VERBOSE) console.log(`[${stamp()}] writing...`);
  const tWrite0 = Date.now();

  for (const p of plans) {
    // バックアップ（DRY=false の場合のみ実ファイル作成）
    let actualBackup = p.backupPath;
    if (!DRY) {
      let tryPath = actualBackup;
      let i = 2;
      while (true) {
        try {
          await fs.writeFile(tryPath, p.backupContent, { flag: 'wx' });
          actualBackup = tryPath;
          break;
        } catch (e: any) {
          if (e && e.code === 'EEXIST') {
            tryPath = path.join(p.dir, `${p.stem}${p.ext}.backup.${i++}`);
            continue;
          }
          throw e;
        }
      }
    }
    console.log(`BACKUP:  ${rel(p.absPath, ROOT_ABS)} -> ${rel(actualBackup, ROOT_ABS)}`);

    for (const f of p.symbolFiles) {
      if (!DRY) await fs.writeFile(f.path, f.content, 'utf8');
      console.log(`WRITE:   ${rel(f.path, ROOT_ABS)}`);
    }

    if (!DRY) await fs.writeFile(p.shimPath, p.shimContent, 'utf8');
    console.log(`SHIM:    ${rel(p.shimPath, ROOT_ABS)}`);
  }

  // index.ts（型onlyに export type を使う）
  for (const [dir, map] of dirIndex.entries()) {
    const indexPath = path.join(dir, 'index.ts');
    const entries = Array.from(map.entries()).sort(([a], [b]) => a.localeCompare(b));
    const lines = entries.map(([n, isType]) =>
      isType ? `export type { ${n} } from './${n}';` : `export { ${n} } from './${n}';`
    );
    const content = lines.join('\n') + '\n';
    if (!DRY) await fs.writeFile(indexPath, content, 'utf8');
    console.log(`INDEX:   ${rel(indexPath, ROOT_ABS)} (${entries.length} symbols)`);
  }

  if (TRACE) {
    const dur = ((Date.now() - tWrite0) / 1000).toFixed(2);
    console.log(`[${stamp()}] write done in ${dur}s`);
  }

  // console.log(DRY ? '\n[Dry Run] 変更は未反映です。--dry-run=false で実行します。' : '\nDone.');
  // BACKUP ログ
  if (DRY) {
    console.log(`PLAN BACKUP: ${rel(p.absPath, ROOT_ABS)} -> ${rel(p.backupPath, ROOT_ABS)}`);
  } else {
    // 既存のバックアップ作成ロジック（実際に書く）
    console.log(`BACKUP:      ${rel(p.absPath, ROOT_ABS)} -> ${rel(actualBackup, ROOT_ABS)}`);
  }

  // WRITE ログ
  for (const f of p.symbolFiles) {
    if (DRY) {
      console.log(`PLAN WRITE:  ${rel(f.path, ROOT_ABS)}`);
    } else {
      await fs.writeFile(f.path, f.content, 'utf8');
      console.log(`WRITE:       ${rel(f.path, ROOT_ABS)}`);
    }
  }

  // SHIM ログ
  if (DRY) {
    console.log(`PLAN SHIM:   ${rel(p.shimPath, ROOT_ABS)}`);
  } else {
    await fs.writeFile(p.shimPath, p.shimContent, 'utf8');
    console.log(`SHIM:        ${rel(p.shimPath, ROOT_ABS)}`);
  }

  // index.ts 生成部も同様に
  if (DRY) {
    console.log(`PLAN INDEX:  ${rel(indexPath, ROOT_ABS)} (${entries.length} symbols)`);
  } else {
    await fs.writeFile(indexPath, content, 'utf8');
    console.log(`INDEX:       ${rel(indexPath, ROOT_ABS)} (${entries.length} symbols)`);
  }
}

main().catch((e: unknown) => {
  console.error(e instanceof Error ? `${e.name}: ${e.message}\n${e.stack ?? ''}` : String(e));
  process.exit(1);
});
