import { createTsupConfig } from "../../tsup.base.config";

export default createTsupConfig({
  entry: {
    index: 'src/index.ts',
    'services/index': 'src/services/index.ts',
    'worker/index': 'src/worker/factory/index.ts',
  },
  dts: {
    entry: {
      index: 'src/index.ts',
      'services/index': 'src/services/index.ts',
      'worker/index': 'src/worker/factory/index.ts',
    },
  },
  external: [
    '@deck.gl/aggregation-layers',
    '@deck.gl/aggregation-layers/*',
    '@deck.gl/core',
    '@deck.gl/core/*',
    '@deck.gl/extensions',
    '@deck.gl/extensions/*',
    '@deck.gl/geo-layers',
    '@deck.gl/geo-layers/*',
    '@deck.gl/layers',
    '@deck.gl/layers/*',
    '@deck.gl/mapbox',
    '@deck.gl/mapbox/*',
    '@deck.gl/mesh-layers',
    '@deck.gl/mesh-layers/*',
    '@emotion/react',
    '@emotion/react/*',
    '@emotion/styled',
    '@emotion/styled/*',
    '@hierarchidb/common-api',
    '@hierarchidb/common-api/*',
    '@hierarchidb/common-types',
    '@hierarchidb/common-types/*',
    '@hierarchidb/plugin-types',
    '@hierarchidb/plugin-types/*',
    '@hierarchidb/runtime-client',
    '@hierarchidb/runtime-plugin-dialog',
    '@hierarchidb/runtime-plugin-dialog/*',
    '@hierarchidb/runtime-worker',
    '@hierarchidb/ui-map',
    '@hierarchidb/ui-map/*',
    '@hierarchidb/ui-treeconsole-base',
    '@hierarchidb/ui-treeconsole-base/*',
    '@hierarchidb/util',
    '@hierarchidb/util/*',
    '@mui/icons-material',
    '@mui/icons-material/*',
    '@mui/material',
    '@mui/material/*',
    'comlink',
    'dexie',
    'react',
    'react-dom',
  ],});
