export {
  ShapeDB,
  ShapeDatabase,
  type BatchProcessConfig,
  type BatchSessionConfig,
  type BatchSessionRecord,
  type BatchTaskType,
  type BatchTaskRecord,
  type CacheEntryRecord,
  type CacheStatistics,
  type FeatureBufferRecord,
  type FeatureIndexRecord,
  type FeatureRecord,
  type LayerInfo,
  type ProcessingStage,
  type ProgressInfo,
  type ResourceUsage,
  type StageStatus,
  type TaskStatus,
  type TileBufferRecord,
  type VectorTileRecord,
  shapeDB,
} from './ShapeDB.js';
export {
  EphemeralShapeDB,
  type BatchSessionMetadata,
  type EphemeralStage,
  type ProcessingCache,
  type RawFeatureBuffer,
  type SimplifiedFeatureBuffer,
  type VectorTileData,
  closeEphemeralShapeDB,
  getEphemeralShapeDB,
} from './EphemeralShapeDB.js';
export type { ShapeMutationAPI, ShapeQueryAPI } from '@hierarchidb/plugin-service-api';
