export {
  ShapeDB,
  ShapeDatabase,
  type BatchProcessConfig,
  type BatchSessionConfig,
  type BatchSessionRecord,
  type DownloadTaskInputData,
  type DownloadTaskOutputData,
  type Extract1TaskInputData,
  type Extract1TaskOutputData,
  type Extract2TaskInputData,
  type Extract2TaskOutputData,
  type VectorTileTaskInputData,
  type VectorTileTaskOutputData,
  type ShapeBatchTaskInputData,
  type ShapeBatchTaskOutputData,
  type BatchTaskType,
  type BatchTaskRecord,
  type CacheEntryRecord,
  type CacheStatistics,
  type FeatureBufferRecord,
  type FeatureIndexRecord,
  type FeatureRecord,
  type LayerInfo,
  type ProcessingStage,
  type ProgressInfo,
  type ResourceUsage,
  type StageStatus,
  type TaskStatus,
  type TileBufferRecord,
  type VectorTileRecord,
  shapeDB,
} from './ShapeDB.js';
export {
  EphemeralShapeDB,
  type BatchSessionMetadata,
  type EphemeralStage,
  type Extract1SourceBuffer,
  type Extract2SourceBuffer,
  type ProcessingCache,
  type RawFeatureBuffer,
  type VectorTileData,
  type VectorTileSourceBuffer,
  type TileIdToBufferRelation,
  closeEphemeralShapeDB,
  getEphemeralShapeDB,
} from './EphemeralShapeDB.js';
export type { ShapeMutationAPI, ShapeQueryAPI } from '@hierarchidb/plugin-service-api';
