/**
 * Shape plugin constants
 */

import type { DataSourceConfig } from './data-source.js';

import type { ShapeBuildConfig } from './build.js';

export const DEFAULT_BUILD_CONFIG: ShapeBuildConfig = {
  dataSourceName: 'geoboundaries',
  fetchConfig: {
    maxConcurrent: 2,
    deleteOnComplete: false,
    timeoutMs: 300000,
    retryAttempts: 3,
    retryDelay: 1000,
    retryLimit: 3,
    retryBackoff: 'linear',
  },
  transformConfig: {
    zoomBandBoundaries: [0, 3, 6],
    maxConcurrent: 2,
    enableFeatureFiltering: true,
    featureAreaThreshold: 1.0,
    minVertexCountForAreaFilter: 10,
    aspectRatioThreshold: 5,
    featureFilterMethod: 'hybrid',
    hybridFilterConfig: {
      quickRejectThreshold: 0.002,
      regularShapeMinRatio: 0.5,
      regularShapeMaxRatio: 2.0,
      simpleShapeVertexThreshold: 10,
      elongatedShapeCorrectionFactor: 1.3,
    },
    deleteOnComplete: false,
    quantize: 1,
    tolerance: 0.1,
    areaThreshold: 1.0,
    excludePolygonAreaCoefficient: 1,
    omitDetailsConfig: {
      level: 'strong',
    },
    selfIntersectionTuningConfig: {
      disableAtZoomOrBelow: 6,
      maxVerticesForFix: 20000,
      maxVerticesForSplit: 5000,
    },
    ringFixConfig: {
      minRingVertices: 4,
      minRingAreaMultiplier: 1.0,
      removeDuplicateConsecutivePoints: true,
      removeCollinearPoints: false,
    },
    selfIntersectionConfig: {
      strategy: 'keep_largest',
      minPolygonAreaMultiplier: 1.0,
      maxPolygons: 1,
      retainHoles: false,
      snapToleranceMultiplier: 1.0,
    },
    preSimplifyFilterConfig: {
      excludeInvalidGeometry: true,
      dropInvalidHoles: true,
      splitSelfIntersections: true,
      dropSmallPolygons: true,
      maxVerticesPerFeature: 200000,
    },
    transformMode: 'simplify-only',
    boundaryDisableAtZoomOrAbove: 3,
  },
  vtConfig: {
    enableTopojsonSimplify: true,
    maxConcurrent: 1,
    dynamicConcurrency: {
      enabled: true,
      minConcurrent: 1,
      highWatermark: 0.85,
      lowWatermark: 0.6,
      adjustStep: 1,
      sampleMs: 2000,
    },
    tolerance: 0,
    extent: 4096,
    bufferSize: 256,
    boundaryDedupe: false,
    indexMaxPoints: 0,
    layerSetName: 'shape',
    promoteId: 'id',
    tileSize: 256,
    inputFormat: 'geojson',
    inputCompression: 'none',
    tileExpandFactor: 1,
    tileExpandMargin: 0,
    format: 'mvt',
    compression: 'gzip',
  },
  cleanupConfig: {
    deleteFetchCeche: false,
    deleteTransformCache: false,
    deleteVTCache: false,
  },
} as const;

export const SHAPE_DATA_SOURCES = [
  {
    name: 'naturalearth' as DataSourceConfig['name'],
    displayName: 'Natural Earth',
    description: 'Free vector and raster map data at 1:10m, 1:50m, and 1:110m scales',
    license: 'Public Domain',
    licenseUrl: 'https://www.naturalearthdata.com/about/terms-of-use/',
    attribution: 'Made with Natural Earth',
    color: '#2E8B57',
    icon: '🌍',
    maxAdminLevel: 2,
    //countryCodeFormat: 'iso2',
  },
  {
    name: 'geoboundaries' as DataSourceConfig['name'],
    displayName: 'geoBoundaries',
    description: 'Open administrative boundaries for all countries',
    license: 'CC BY 4.0',
    licenseUrl: 'https://geoboundaries.org/globalLicense.html',
    attribution: 'geoBoundaries Global Database',
    color: '#4169E1',
    icon: '🗺️',
    maxAdminLevel: 5,
    countryCodeFormat: 'iso3',
  },
  {
    name: 'gadm' as DataSourceConfig['name'],
    displayName: 'GADM',
    description: 'Global Administrative Areas database',
    license: 'Custom (Academic Use)',
    licenseUrl: 'https://gadm.org/license.html',
    attribution: 'GADM.org',
    color: '#FF6347',
    icon: '🌐',
    maxAdminLevel: 4,
    countryCodeFormat: 'iso3',
  },
  {
    name: 'openstreetmap' as DataSourceConfig['name'],
    displayName: 'OpenStreetMap',
    description: 'Community-driven geographic data',
    license: 'ODbL',
    licenseUrl: 'https://opendatacommons.org/licenses/odbl/',
    attribution: '© OpenStreetMap contributors',
    color: '#7EDD00',
    icon: '🛣️',
    maxAdminLevel: 3,
    countryCodeFormat: 'iso2',
  },
] as DataSourceConfig[];
